### ISSUE TITLE
boot-bitcode-pathnames bogus

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1005]
* https://github.com/clasp-developers/clasp/blob/master/src/lisp/kernel/cmp/cmpbundle.lsp#L411
* uses undefined function `core::get-pathname-with-type``
* uses `core::select-source-files`which is defined in `clasp-builder.lsp`but not in the final image
* boot-bitcode-pathnames is not called 
* I can't undestand what role this function should play in cmpbundle

I propose to delete boot-bitcode-pathnames

**Comment by Bike** [comment]
gave it a shot.
