### ISSUE TITLE
ansi test regression: find-method with eql specializers fail

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1016]
```lisp
(defgeneric find-method-gf-02 (x))

#<STANDARD-GENERIC-FUNCTION FIND-METHOD-GF-02>
(defmethod find-method-gf-02 ((x (eql 1234567890))) 'a)

#<STANDARD-METHOD FIND-METHOD-GF-02 ((EQL 1234567890))>
(find-method #'find-method-gf-02 nil (list '(eql 1234567890)))

Condition of type: SIMPLE-ERROR
There is no method on the generic function FIND-METHOD-GF-02 that agrees on qualifiers NIL and specializers ((EQL 1234567890))
Available restarts:
(use :r1 to invoke restart 1, etc.)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.


(FIND-METHOD #<STANDARD-GENERIC-FUNCTION FIND-METHOD-GF-02> NIL ((EQL 1234567890)))
````

**Comment by kpoeck** [comment]
I believe the fix is this:
```lisp
(defun find-method (gf qualifiers specializers &optional (errorp t))
  (declare (notinline method-qualifiers))
  (flet ((filter-specializer (name)
	   (cond ((typep name 'specializer)
		  name)
		 ((atom name)
		  (let ((class (find-class name nil)))
		    (unless class
		      (error "~A is not a valid specializer name" name))
		    class))
		 ((and (eq (first name) 'EQL)
		       (null (cddr name)))
		  (clos:intern-eql-specializer (cadr name)))
		 (t
		  (error "~A is not a valid specializer name" name))))
	 (specializer= (cons-or-class specializer)
           (eq cons-or-class specializer)))
    (when (/= (length specializers)
	      (length (generic-function-argument-precedence-order gf)))
      (error
       "The specializers list~%~A~%does not match the number of required arguments in ~A"
       specializers (generic-function-name gf)))
    (loop with specializers = (mapcar #'filter-specializer specializers)
       for method in (generic-function-methods gf)
       when (and (equal qualifiers (method-qualifiers method))
		 (every #'specializer= specializers (method-specializers method)))
       do (return-from find-method method))
    ;; If we did not find any matching method, then the list of
    ;; specializers might have the wrong size and we must signal
    ;; an error.
    (when errorp
      (error "There is no method on the generic function ~S that agrees on qualifiers ~S and specializers ~S"
	     (generic-function-name gf)
	     qualifiers specializers)))
  nil)
````

The fix being `(clos:intern-eql-specializer (cadr name)))`

**Comment by Bike** [comment]
Does `find-method` have to work with these eql specializer designators? that's not clear to me from CLHS

**Comment by kpoeck** [comment]
Not a language lawyer but:

The generic function find-method takes a generic function and returns the method object that agrees on qualifiers and parameter specializers with the method-qualifiers and specializers arguments of find-method. Method-qualifiers contains the method qualifiers for the method. The order of the method qualifiers is significant. For a definition of agreement in this context, see Section 7.6.3 Agreement on Parameter Specializers and Qualifiers.

and in 7.6.3
7.6.3 Agreement on Parameter Specializers and Qualifiers
Two methods are said to agree with each other on parameter specializers and qualifiers if the following conditions hold:
1. Both methods have the same number of required parameters. Suppose the parameter specializers of the two methods are P1,1 ... P1,n and P2,1 ... P2,n.
2. For each 1 <= i <= n, P1,i agrees with P2,i. The parameter specializer P1,i agrees with P2,i if P1,i and P2,i are the same class or if P1,i=(eql object1), P2,i=(eql object2), and (eql object1 object2). Otherwise P1,i and P2,i do not agree.
3. The two lists of qualifiers are the same under equal.

The section 2 here seem to indicate that eql parameters should be considered

**Comment by kpoeck** [comment]
Anyhow filter-specializer is clearly prepared for eql specializers, but now doing the wrong thing. Do you see any problem with my fix?

**Comment by Bike** [comment]
I guess there's no harm in letting `find-method` accept eql specializers. If we adopt one of the specializer extensions later it might take some more thought.

Your fix looks fine. I'll put it in. The existing code that uses `(cdr name)` instead of `(intern-eql-specializer (second name))` is probably a remnant of when CLOS used lists to indicate eql specialization. I tried to remove that everywhere but evidently I missed a few bits.
