### ISSUE TITLE
typo in compute-constructor: Undefined variable CLASS-NAME

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1017]
should be
`(undefined-constructor class-designator)`
instead of `(undefined-constructor class-name)`

**Comment by kpoeck** [comment]
https://github.com/clasp-developers/clasp/blob/master/src/lisp/kernel/clos/static-gfs/compute-constructor.lisp#L37

**Comment by Bike** [comment]
oh whoops i fixed this but didn't push it

**Comment by Bike** [comment]
b91fda5e0e1534a7e7aa941ba0a5459b00530260

**Comment by kpoeck** [comment]
was already fixed when I reported, sorry for the noise

**Comment by Bike** [comment]
It wasn't fixed on github. I committed a fix to my local repo before you posted this but only pushed it after this issue reminded me to.
