### ISSUE TITLE
regenerate-cleavir-file-list bases paths off the current executables source tree

### ISSUE THREAD

**Issue by karlosz** [clasp-developers/clasp#1020]
It would be better to grovel based on the pathname of the file being loaded, otherwise using an executable installed into a different location will not use the intended paths.

**Comment by kpoeck** [comment]
```lisp
(load (make-pathname
       :name "asdf-system-groveler"
       :type "lisp"
       :defaults (or *load-truename* *compile-file-truename*)))
````

is probably what karlosz needs

**Comment by kpoeck** [comment]
oops alexandria is wrong, need another fix
