### ISSUE TITLE
Should initialize-instance always return the newly created object?

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1031]
consider compiling:
```lisp
(defclass foo ()
  ((a :initform :a)))

(defmethod initialize-instance ((me foo) &rest initargs &key policy provider (hash-test 'eql) &allow-other-keys)
  (declare (ignore initargs))
  (call-next-method)
  23)

(defun test ()
  (make-instance 'foo :a 1))
 
````
```lisp
in a repl
(test) -> 23
````

**Comment by kpoeck** [comment]
in sbcl:
```lisp
CL-USER> (test)
#<FOO {10034CBD33}>
````

**Comment by kpoeck** [comment]
I believe this is undefined behaviour, happened in https://github.com/jlahd/cacle/blob/master/src/cache.lisp#L26

**Comment by Bike** [comment]
clhs 7.1.7 maybe implies that `make-instance` should return the result of `allocate-instance`, rather than relying on `initialize-instance` to be what it's supposed to be. doing so shouldn't be inefficient or anything so i'll go ahead and do it.

**Comment by Bike** [comment]
c8a22134b732592634210f53c1c10d15014e6c8b

**Comment by kpoeck** [comment]
fixed as indicated
