### ISSUE TITLE
ansi-test the.4 and others fails with high safety

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1054]
short version:
```lisp
COMMON-LISP-USER> (declaim (optimize (COMPILATION-SPEED 1) (DEBUG 1) (SPACE 1) (SPEED 1) (SAFETY 3)))

((CLASP-CLEAVIR::SAVE-REGISTER-ARGS . T)
 (CLASP-CLEAVIR::INSERT-TYPE-CHECKS . T) (CORE::INSERT-ARRAY-BOUNDS-CHECKS . T)
 (EXT:ASSUME-RIGHT-TYPE) (CLASP-CLEAVIR::DO-TYPE-INFERENCE)
 (CLASP-CLEAVIR::DO-DX-ANALYSIS) (CLEAVIR-ESCAPE:TRUST-DYNAMIC-EXTENT))
COMMON-LISP-USER> (eval `(the ,(type-of :a) (quote :a)))

T
COMMON-LISP-USER> (declaim (optimize (COMPILATION-SPEED 1) (DEBUG 1) (SPACE 1) (SPEED 1) (SAFETY 1)))

((CLASP-CLEAVIR::SAVE-REGISTER-ARGS . T) (CLASP-CLEAVIR::INSERT-TYPE-CHECKS)
 (CORE::INSERT-ARRAY-BOUNDS-CHECKS . T) (EXT:ASSUME-RIGHT-TYPE)
 (CLASP-CLEAVIR::DO-TYPE-INFERENCE) (CLASP-CLEAVIR::DO-DX-ANALYSIS)
 (CLEAVIR-ESCAPE:TRUST-DYNAMIC-EXTENT))
COMMON-LISP-USER> (eval `(the ,(type-of :a) (quote :a)))

:A
````

this might also be the cause of #1051

**Comment by Bike** [comment]
that's probably going to do with this: https://github.com/clasp-developers/clasp/blob/master/src/lisp/kernel/cleavir/convert-special.lisp#L119-L158

i can't say what the problem is, though. maybe the m-v-extract form is being miscompiled.

**Comment by kpoeck** [comment]
If I change cleavir-cst-to-ast:type-wrap to ignore insert-type-checks, than this no longer fails (neither 1051)

How can I see how `cleavir-primop:multiple-value-extract` is being compiled?

**Comment by Bike** [comment]
It's a special operator. The semantics are that `(multiple-value-extract (...) form forms...)` is equivalent to `(let ((#1=#:temp (multiple-value-list ,form))) (multiple-value-bind (...) (values-list #1#) ,@forms) (values-list #1#))`, except with less consing. The code for it is in Cleavir.

**Comment by kpoeck** [comment]
does not happen anymore
