### ISSUE TITLE
setf svref/no-bounds-check referenced but not defined in inline.lisp

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1091]
* testing clx I got an error `The function (SETF SVREF/NO-BOUNDS-CHECK) is undefined.
   [Condition of type UNDEFINED-FUNCTION]`
* probably here: https://github.com/clasp-developers/clasp/blob/bir/src/lisp/kernel/cleavir/inline.lisp#L629-#L633
* Is assume this should be preceeded by #+(or)

**Comment by Bike** [comment]
yeah, that should be dummied out. i can do that

**Comment by kpoeck** [comment]
Please do so
