### ISSUE TITLE
Up-to-date build instructions? (trying fedora)

### ISSUE THREAD

**Issue by guicho271828** [clasp-developers/clasp#1104]
I started trying to build clasp on Fedora 32. I see a couple of inconsistent version requirement here and there...
For example, https://github.com/clasp-developers/externals-clasp still mentions llvm 4.
Fedora 32 / dnf contains clang7 and onwards up to clang10 (default).
I read that clang9 is the currently supported version, correct?
I wish the instruction is kept is centralized in a single place and particularly the clang version should not be mentioned elsewhere.

Here is the fedora equivalent of dependent packages I managed to assemble:
```
sudo dnf install -y gcc g++ llvm9.0 llvm9.0-devel llvm9.0-libs llvm9.0-static clang9.0-devel clang9.0-libs cmake gc-devel gmp-devel \
     binutils-gold binutils-devel zlib-devel ncurses-devel boost-devel \
     boost-filesystem boost-regex boost-date-time boost-program-options boost-system \
     boost-iostreams libunwind-devel xz-devel elfutils-libelf-devel libbsd-devel sbcl \
     waf
```

**Comment by kpoeck** [comment]
To the best of my knowledge, the best build instructions are here: https://github.com/clasp-developers/clasp/wiki/Road-to-clasp-with-lvm@9

Should there be an error, please comment here and we fix the instructions:

 externals-clasp is not needed, the right llvm version is 9

**Comment by guicho271828** [comment]
Would you consider removing mentions to old versions, to minimize surprise?

**Comment by guicho271828** [comment]
llvm-config issue on Fedora
related: https://github.com/mesonbuild/meson/issues/5059

**Comment by guicho271828** [comment]
It is installed on 
/usr/bin/llvm-config-9.0-64

**Comment by guicho271828** [comment]
#1105

**Comment by kpoeck** [comment]
In the channel log I see that users had this issue a couple of times, but can't find a resolution. @karlosz I believe you reported that too, do you remember how you solved that?

**Comment by karlosz** [comment]
Yes, you have to remove --link-static from the wscript. (There should be only one instance of it.)

**Comment by guicho271828** [comment]
reflected in 168fcc2

**Comment by guicho271828** [comment]
Good, after removing --link-static the build succeeded.
How should I run unit tests?

**Comment by kpoeck** [comment]
* ./waf test or 
* make test 

to run the unit test

some failures are normal

**Comment by guicho271828** [comment]
```
Passes: 1584
Fails:  24

Failed tests (FINALIZERS-CONS SBCL-CROSS-COMPILE-4 INCLUDE-LEVEL-2A
              INCLUDE-LEVEL-2B INCLUDE-LEVEL-3 DISASSEMBLE-8 DISASSEMBLE-9
              READ-SYMBOL.19 READ-SUPPRESS.17 CLHS-23.2.16
              PRINT.VECTOR.RANDOM.1.TAKE.1 PRINT.VECTOR.RANDOM.1.TAKE.2
              PRINT.ARRAY.RANDOM.1.TAKE.1 PRINT.ARRAY.RANDOM.1.TAKE.2
              READ-PRINT-CONSISTENCY-ARRAYS TYPES-CLASSES-10 LOOP-FIXNUM-1
              LOOP-FINALLY-1 LOOP-FINALLY-2 LOOP-FINALLY-3 LOOP-FINALLY-4
              COMPILE-FILE-NO-UNWIND COMPILE-FILE-PATHNAME-2A
              COMPILE-FILE-PATHNAME-2B)

unexpected failures (FINALIZERS-CONS DISASSEMBLE-8 DISASSEMBLE-9
                     COMPILE-FILE-NO-UNWIND COMPILE-FILE-PATHNAME-2A
                     COMPILE-FILE-PATHNAME-2B)
```
ok, thanks for the help.
please review the pull request on your convenience.

**Comment by kpoeck** [comment]
I am just surprised by the 2 disassemble errors (don't have them at macosx) , the rest is fine. Can't merge myself, but will try your 2 requests
