### ISSUE TITLE
2 ansi regressions for loop

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1109]
With newest clasp including https://github.com/clasp-developers/clasp/pull/1108
the following two tests hang (without the pr the tests error much earlier)
* loop.13.29 `(loop named foo for i = 1 then (return-from foo :good))`
* loop.13.69 `(block nil
    (loop named foo for i on '(a b c) by (return :good) return :bad)
    :bad)`

**Comment by karlosz** [comment]
the was also fixed by latest cleavir

**Comment by kpoeck** [comment]
fixed with latest cleavr as karlosz says

**Comment by Bike** [comment]
5007a4715f6354e9222848458c3d9a1bfa737442 for reference
