### ISSUE TITLE
ansi-test-regression: CERROR.6 -> Condition of type: WRONG-NUMBER-OF-ARGUMENTS

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1112]
```lisp
(locally (declare (optimize (safety 3)))(HANDLER-BIND ((SIMPLE-ERROR #'(LAMBDA (C) (CONTINUE C))))
                    (PROGN (CERROR "Wooo" 'SIMPLE-ERROR) 10)))
Condition of type: WRONG-NUMBER-OF-ARGUMENTS
Calling (LAMBDA (CHECKED23392 &REST IGNORE)) - Got 0 arguments, but expected exactly 1
Available restarts:
(use :r1 to invoke restart 1, etc.)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
````

**Comment by Bike** [comment]
We have a type declaration on `cerror` saying it returns `nil`, which is what the CLHS says, but it actually returns no values. I can fix. Not sure we're handling fuzziness correctly then, though

**Comment by Bike** [comment]
Now returns 10.

**Comment by kpoeck** [comment]
Fix looks about right, compiling

**Comment by karlosz** [comment]
Yeah, looks like the fuzziness is wrong. Kicking the can down the road since the type check machinery will probably have to be redone. (It doesn't check multiple values and pass them out properly at the moment).
