### ISSUE TITLE
More-conditions: simple-condition-format-control madness

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1138]
```lisp
(in-package :cl-user)

(defun maybe-print-explanation-a (stream condition)
  (if 
   (simple-condition-format-control condition)
   (list :ok stream (simple-condition-format-control   condition))
   :nok))

(defun maybe-print-explanation-b (stream condition)
  (if (slot-value (make-instance 'simple-condition :FORMAT-CONTROL nil) 'core::format-control)
      (list :ok stream (simple-condition-format-control   condition))
      :nok))

(defun gives-wrong-answer ()
  (values
   `(wrong, (maybe-print-explanation-a t
                                       (make-instance 'simple-condition :FORMAT-CONTROL nil)))
  `(right, (maybe-print-explanation-b t
                                      (make-instance 'simple-condition :FORMAT-CONTROL nil)))))
````

And test
```lisp
COMMON-LISP-USER> (gives-wrong-answer)

(WRONG (:OK T NIL))
(RIGHT :NOK)
`````
* `(simple-condition-format-control condition)` is nil, but the (if (simple-condition-format-control condition) ..) takes the path as if `(simple-condition-format-control condition)`  would be true
* Does not happen with `slot-value`

**Comment by Bike** [comment]
I think this is because we have a type declaration saying that `simple-condition-format-control` returns a format control, and format controls are never NIL. So either that type declaration is invalid, or we should signal an error when something other than a format control is given to `make-condition`.

**Comment by kpoeck** [comment]
Yes, I disabled the declaration and the code works as expected. Looking at clhs I am not totally sure that :format-control can't be nil (probably was meant like this)

**Comment by kpoeck** [comment]
The code that produces the situation is here:
https://github.com/scymtym/more-conditions/blob/master/src/conditions.lisp#L303

Kind of ironic that it has a #-sbcl , no idea why scymtym did that

**Comment by Bike** [comment]
I think it would be weird for the format control to be NIL, since it is after all intended for format, and `(format nil nil ...)` is invalid.

But also I don't see any issue with removing this declaration given that it will never be useful for optimization ever.
