### ISSUE TITLE
equalp failure on displaced array

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#1143]
`(equalp (make-array 6 :element-type 'bit :displaced-to #*110110111) #(1 1 0 1 1 0))` => `nil`

If you reverse the arguments it works, so I suspect `MDArray_O::equalp` is busted, but don't see a problem.

**Comment by kpoeck** [comment]
looks like it goes through `BitVectorNs_O::equal` and not MDArray_O::equalp.

both the test for `(BitVectorNs_sp strns = other.asOrNull<BitVectorNs_O>())`
and `(SimpleBitVector_sp ss = other.asOrNull<SimpleBitVector_O>())`
seem to fail so it returns `false`

**Comment by kpoeck** [comment]
and the argument is neither a Bitvector nor a SimpleBitVector so the code in BitVectorNs_O::equal seems to be wrong (or `Bitvector::equalp` should not do return `this->equal(other);`

**Comment by kpoeck** [comment]
@Bike I believe this is wrong: https://github.com/clasp-developers/clasp/blob/master/include/clasp/core/array_bit.h#L102

Should be the following condition
`If two arrays have the same number of dimensions, the dimensions match, and the corresponding active elements are equalp.`

**Comment by Bike** [comment]
ah-ha. yeah, that does look wrong. i'll try removing it. the general MDArray::equalp function can handle it hopefully
