### ISSUE TITLE
COMPILE-FILE with a non-existent source file generates an unhelpful error

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#115]
> (compile-file "/tmp/foo")

Condition of type: SIMPLE-PROGRAM-ERROR
The only argument for pathname is nil

Available restarts:
(use :r1 to invoke restart 1)
1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[149] TOP-LEVEL.
 File: "-unknown-file-" (Position #0)

**Comment by Shinmera** [comment]
Can confirm on b05884f.

**Comment by Bike** [comment]
Prints something decent as of 79542139c.
