### ISSUE TITLE
waf: build future branch on MacOS, where vtable symbols for template classes are hidden/local

### ISSUE THREAD

**Issue by attila-lendvai** [clasp-developers/clasp#1161]
It's basically:
1. build iclasp-boehmprecise and compile the common lisp code for cclasp
2. run iclasp-boehmprecise  loading cclasp common lisp image with a special flag and build a symbol list and save it to a file
3. LINK an executable called "cclasp-boehmprecise" that uses the new symbol list.
4. new build stuff that saves snapshots and links new executables that have the snapshots embedded within them.

Right now - when I go:  `./waf distclean configure build_cboehmprecise` it crashes very quickly with the following error message/backtrace: https://gist.github.com/drmeister/64e9e4e4567662679e60da2a0155f2e1

LLVM commit used: `7ee96429a0b057bcc97331a6a762fc3cd00aed61`

**Comment by drmeister** [comment]
It turns out that you need to be building cando for the problem to show up.   

Building clasp by itself works fine.
`./waf build_cboehmprecise`
```$ ./build/boehmprecise/cclasp-boehmprecise
(gctools:slad)``` -> generates test.snapshot
```$ ./build/boehmprecise/cclasp-boehmprecise -T snapshot -i test.snapshot
../../src/main/main.cc:355:startup Loading the snapshot test.snapshot
../../src/gctools/imageSaveLoad.cc:1521:updateRelocationTableAfterLoad  Library /Users/su-chris/Development/clasp-future/./build/boehmprecise/cclasp-boehmprecise contains 5082 grouped pointers
../../src/gctools/imageSaveLoad.cc:2512:image_load Releasing temporary roots
../../src/gctools/imageSaveLoad.cc:2524:image_load munmap'ing loaded image - filling with 0xc0
Top level in: #<PROCESS TOP-LEVEL @0x10f0dbea1 (Running)>.
COMMON-LISP-USER> 
```

**Comment by drmeister** [comment]
It turns out the problem was in the cando wscript file - it wasn't updated to handle the changes in the main clasp wscript file.
