### ISSUE TITLE
Returning abort restart causes segmentation-violation

### ISSUE THREAD

**Issue by yitzchak** [clasp-developers/clasp#1179]
Calling the abort function appears to cause this although executing the equivalent code doesn't.

```
Starting cclasp-boehmprecise-0.4.2-4548-g80d9caef9-cst ... loading image...
Top level in: #<PROCESS TOP-LEVEL @0x7fc7d6f2ff09 (Running)>.
COMMON-LISP-USER>> (restart-bind ((abort (lambda ()))) (abort))

Debugger received error of type: SEGMENTATION-VIOLATION

COMMON-LISP-USER>> (restart-bind ((abort (lambda ()))) (invoke-restart (system::coerce-restart-designator 'abort)))

NIL
```

**Comment by Bike** [comment]
Weird. I don't suppose there's a backtrace?

**Comment by yitzchak** [comment]
```
SEGMENTATION-VIOLATION: Segmentation fault. Attempted to access resticted memory address #x0.

This is due either to a problem in foreign code (e.g., C++), or a bug in Clasp itself.

4: (EXT:SEGMENTATION-VIOLATION 0)
9: ((LAMBDA NIL))
11: (JUPYTER/COMMON-LISP::EVAL-AND-PRINT)
13: ((METHOD JUPYTER:EVALUATE-FORM (JUPYTER/COMMON-LISP:KERNEL T T T)))
26: (JUPYTER/COMMON-LISP::REPL)
28: ((METHOD JUPYTER:EVALUATE-CODE (JUPYTER/COMMON-LISP:KERNEL T)))
39: (JUPYTER::HANDLE-EXECUTE-REQUEST)
44: (CORE:CATCH-FUNCTION)
48: (CORE:CATCH-FUNCTION)
49: (JUPYTER::RUN-SHELL)
51: ((LAMBDA NIL))
54: (CORE:PROGV-FUNCTION)
55: ((LAMBDA NIL))
```

**Comment by yitzchak** [comment]
Or in the REPL

```
COMMON-LISP-USER>> :b

   4: (EXT:SEGMENTATION-VIOLATION 0)
   9: (LAMBDA NIL)
  11: (METHOD CLASP-CLEAVIR::CCLASP-EVAL-WITH-ENV (T T))
  15: CLASP-CLEAVIR::SIMPLE-EVAL
  16: CLASP-CLEAVIR::CCLASP-EVAL
  17: (FLET CORE::REP)
  21: CORE:CATCH-FUNCTION
  22: CORE::TPL
  27: CORE:CATCH-FUNCTION
  28: CORE:TOP-LEVEL
  29: CORE::CCLASP-TOP-LEVEL
  31: CORE:TOP-LEVEL
  36: NIL
```

**Comment by Bike** [comment]
Well that's unhelpful.

If I had to guess, the problem is that `abort` is declaimed somewhere as having a nil return type, so when it actually returns there's a problem. (`abort` is definitely proclaimed to have such a type, but I'm just guessing about it being the problem.) We should probably make that violated type declaration a little more palatable.

For `abort` specifically, per what you wrote in https://github.com/s-expressionists/wscl/blob/main/wscl-issues/proposed/abort-function we should have it signal a control error if the restart returns. I can get going on that.

**Comment by Bike** [comment]
I put "should fix" in the commit message and it thinks it must be fixed... oh well. Please do verify that the problem is solved. It seems to be for me.

**Comment by yitzchak** [comment]
Are you sure about `muffle-warning`? SBCL seems to allow a return.

**Comment by yitzchak** [comment]
I guess they just don't check for it. You are correct that the CLHS says it doesn't return. Their own implementations seem all `return-from`. Guess I'll check out other implementations and write another issue for WSCL.

**Comment by Bike** [comment]
in the first place, using `restart-bind` at all, let alone making restarts that don't transfer control, is not something i've seen in actual code before. on top of that doing it with standard restarts is unusual, and especially with `muffle-warning`, which in most code is just implicitly bound with `warn`. so this probably hasn't come up much.
