### ISSUE TITLE
BUG: Dynamic environment chain screwed up somehow loading pfdietz random tester

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1216]
```lisp
; caught ERROR:
;   BUG: Dynamic environment chain screwed up somehow
;     at unknown location
; 
Debugger received error of type: SIMPLE-ERROR
BUG: Dynamic environment chain screwed up somehow
Error flushed.
COMMON-LISP-USER> :b

   0: (BREAK "compile error ~a ~%" "random/random-int-form.lsp")
   3: (LAMBDA (&OPTIONAL OUTPUT-TRUENAME WARNINGS-P FAILURE-P &REST #:G8683))
   4: (COMPILE-AND-LOAD "random/random-int-form.lsp")
````

**Comment by kpoeck** [comment]
Happens compiling `test-int-form` at https://github.com/pfdietz/ansi-test/blob/master/random/random-int-form.lsp#L2483

**Comment by kpoeck** [comment]
I know the backtrace is of no help, perhaps you could tell me how to investigate

**Comment by Bike** [comment]
well, first thing i'd do is get rid of that break, wherever it is, so the error can propagate naturally. with compile-file-serial of course

**Comment by Bike** [comment]
I can reproduce this by loading some of the dependencies first.

**Comment by Bike** [comment]
I cannot replicate as of https://github.com/clasp-developers/clasp/commit/49a13056c1f743bf0bb1ad6f1c11b4730587e081 (https://github.com/s-expressionists/Cleavir/commit/40054fdbf8c52381e70ee202531baf4cb0c26d2e). There was an issue in contification explained in the Cleavir commit message that I believe caused this issue.

**Comment by kpoeck** [comment]
Fixed
