### ISSUE TITLE
Configure errors on Arch Linux

### ISSUE THREAD

**Issue by kiranshila** [clasp-developers/clasp#1218]
LLVM and clang are now both at 13 in the Arch repos, so I thought I would give building this a shot.
I was wrestling around with getting `./waf configure` to run, but I was getting a bunch of linking errors when it tries to compile the test programs with all the clang libraries.

```
/usr/bin/ld: cannot find -lclangFrontend
/usr/bin/ld: cannot find -lclangDriver
/usr/bin/ld: cannot find -lclangSerialization
/usr/bin/ld: cannot find -lclangParse
/usr/bin/ld: cannot find -lclangSema
/usr/bin/ld: cannot find -lclangAnalysis
/usr/bin/ld: cannot find -lclangEdit
/usr/bin/ld: cannot find -lclangAST
/usr/bin/ld: cannot find -lclangLex
/usr/bin/ld: cannot find -lclangBasic
```

I have discovered that since clang10, the Arch version of clang does not come with shared libraries at all and short of compiling clang, there isn't an easy way to get them ([source](https://bugs.archlinux.org/task/66283)). I poked around in `wscript` and uncommented https://github.com/clasp-developers/clasp/blob/8bbdc4b1a232bc8aa913c27262836a80f3ac618e/wscript#L149 and commented out all the libraries before as that seems to be the "correct" way to link against them, at least as far as the Arch packaging people are concerned haha.

So far, everything seems to be working. So, it might be worth a patch on the AUR build, considering you don't need to pull in your `llvm13` package anymore either.

**Comment by kiranshila** [comment]
Update built and runs fine!

**Comment by yitzchak** [comment]
Thanks. I am testing on the AUR package and CANDO.

**Comment by yitzchak** [comment]
This should be resolved. The AUR package has been updated.
