### ISSUE TITLE
./waf configure failure - no member named 'setw' in namespace 'std'

### ISSUE THREAD

**Issue by phantomics** [clasp-developers/clasp#1223]
I just tried compiling the `main` and `test` branches and got the same error. The file `src/gctools/boehmGarbageCollection.cc` failed to build with an error message stating "no member named 'setw' in namespace 'std'." Looking for a solution, I found this SO question:

https://stackoverflow.com/questions/18983745/error-message-setw-is-not-defined-using-g

And so i added `#include <iomanip>` at the top of the #include statements in `boehmGarbageCollection.cc` and the problem went away. I'm not sure if this change should be made in the repo or if this problem has another source that I overlooked and adding the header is a mistake..

**Comment by kpoeck** [comment]
The test branch is not current, so you should use `main`.

Just tried and building worked fine on macos and ubuntu.

What is your build environment?

**Comment by phantomics** [comment]
OS is Debian GNU/Linux 10 (buster), kernel is 5.4.0-17.1-liquorix-amd64, using the release versions of LLVM 13, Clang 13 and libc++ 13 downloaded from the repository at http://apt.llvm.org/buster/. Is there anything else that would help to know? 

While adding that line fixed my previous problem, now the build fails when running ./waf build_cboehm -v.  It prints many messages like `/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/typeinfo:100: error: undefined reference to 'typeinfo for clang::X'`. The X refers to different items like `clang::OMPThreadPrivateDecl`, `clang::ObjCPropertyImplDecl` and dozens of others.

**Comment by Bike** [comment]
Could you possibly explain your solution for future reference?

**Comment by Bike** [comment]
gotcha
