### ISSUE TITLE
couldn't find any end-user documentation

### ISSUE THREAD

**Issue by martindemello** [clasp-developers/clasp#1231]
I hunted around, but couldn't find any examples of calling a C++ library from clasp. Could you add an examples directory or a brief howto?

**Comment by Bike** [comment]
Is https://clasp-developers.github.io/clbind-doc.html what you want?

Probably we should link the manual from the readme. the manual then links to this page.

**Comment by kpoeck** [comment]
perhaps also https://github.com/clasp-developers/demo-clasp-cxx-interoperation

**Comment by martindemello** [comment]
thanks, those are helpful! i think the manual (and more generally the entire clasp-developers.github.io site) should indeed be prominently linked to from the README, since the github repo is the top hit when googling "clasp lisp".

**Comment by Bike** [comment]
You're right. I'll do that in a bit.

**Comment by Bike** [comment]
Going to close this now, since the manual is linked from the README and all.
