### ISSUE TITLE
CONTRIBUTING link in README broken in main

### ISSUE THREAD

**Issue by dbenn** [clasp-developers/clasp#1232]
On the main branch, in the CONTRIBUTING link in README.md gives a 404 error. Even though CONTRIBUTING.md is visible in the file list, given that the link is visible along with the rest of the text of README on the repository page, it seems like something you would want to fix. Thanks.

Looks like an interesting project by the way. I wrote a LISP system for the Newton PDA 20 years ago and have always appreciated LISP, even though my bread and butter is C, C++, R, Python etc, and in the scientific computing domain for the last decade.

**Comment by kpoeck** [comment]
the contributing link should be https://github.com/clasp-developers/clasp/blob/main/CONTRIBUTING.md

**Comment by Bike** [comment]
fixed. thanks for the report. documentation is a weak point for us sometimes
