### ISSUE TITLE
Building fail on Arch Linux: building process consume all memory & disk I/O usage

### ISSUE THREAD

**Issue by glyh** [clasp-developers/clasp#1243]
I'm trying to install clasp via AUR package `clasp-cl-git`. But when packaging this from source, the process consume all memory and disk I/O usage on my laptop, and causing it not able to response any user input. As a result I have to manually power it off and restart my laptop. 

Here are some information that might be helpful: 
```
                   -`                    lyh@arch
                  .o+`                   --------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: 82DM Lenovo XiaoXinPro-13ARE 2020
               `+oooooo:                 Kernel: 5.16.0-arch1-1
               -+oooooo+:                Uptime: 12 hours, 6 mins
             `/:-:++oooo+:               Packages: 1516 (pacman)
            `/++++/+++++++:              Shell: fish 3.3.1
           `/++++++++++++++:             Resolution: 2560x1600
          `/+++ooooooooooooo/`           WM: sway
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: alacritty
      :osssssss/        osssso+++.       CPU: AMD Ryzen 7 4800U with Radeon Graphics (16) @ 1.800GHz
     /ossssssss/        +ssssooo/-       GPU: AMD ATI 03:00.0 Renoir
   `/ossssso+/:-        -:/+osssso+-     Memory: 2910MiB / 15421MiB
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/

```

**Comment by ak-coram** [comment]
@glyh: it builds for me, but requires more than 16 gigabytes of memory. It looks like the memory usage is high because multiple components are built at the same time. Have you tried setting `USE_PARALLEL_BUILD` to `False` in `wscript.config` (I believe one could also limit the number of jobs via `waf`) or alternatively adding swap to your system (if you don't have some already)?

**Comment by glyh** [comment]
I have 8G swap partition
```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
nvme0n1     259:0    0 476.9G  0 disk
├─nvme0n1p1 259:1    0   512M  0 part /boot/efi
├─nvme0n1p2 259:2    0     8G  0 part [SWAP]
└─nvme0n1p3 259:3    0 468.4G  0 part /var/lib/docker/btrfs
                                      /home
                                      /mnt/defvol
                                      /
```
I'll try again and report if it succeed.

**Comment by drmeister** [comment]
Try `./waf build_cboehmprecise -j1` - that will build with one core.   If that works then its using too much memory when does the parallel build.   Try different values of -jX to see what your system will tolerate.

Can you tell me at what stage it consumes all memory?  During the C++ compilation or during the Common Lisp compilation.
Clasp build stages go like this:
1. Run the C++ preprocessor on all the C++ code (parallel and controlled by -jX)
2. Compile the C++ code (parallel and controlled by -jX)
3. Link the C++ code to create an executable (I don't know how parallel this is but it does use a lot of memory)
4. Compile aclasp (this is parallel and controlled by -jX)
5. Compile bclasp (this is parallel and controlled by -jX)
6. Compile cclasp (this is parallel and controlled by -jX)

**Comment by yitzchak** [comment]
@glyh You could try doing as @drmeister suggests with the waf invokation by updating the PKGBUILD yourself, provided you are using makepkg not yay or another AUR helper.

I am looking into what updates to PKGBUILD would best so others don't have this issue.

**Comment by yitzchak** [comment]
@glyh Have you had any luck with limiting the number of jobs. One other thing you could try increasing the size of the swap if you have disk space.

**Comment by Bike** [comment]
I have run into this issue before. Yesterday I built without lockup with four jobs (on my hex core machine) and 16 GB of memory. Went pretty smoothly.

**Comment by yitzchak** [comment]
I am considering doing something like this in the PKGBUILD.

```
./waf --jobs=$(($(nproc) / 2)) build_dboehmprecise
```

**Comment by yitzchak** [comment]
@glyh I pushed some changes to the PKGBUILD that limit the number of jobs to half of the available cores. Hopefully that will fix your issue.

**Comment by glyh** [comment]
@yitzchak Thank you. With your new PKGBUILD and more swap space, I build it successfully! I'm closing this.
