### ISSUE TITLE
Strange bug affecting MaxPC parser library

### ISSUE THREAD

**Issue by phantomics** [clasp-developers/clasp#1245]
This is a strange one. Some parsing functions within the MaxPC library fail in some situations. Perhaps a problem related to iteration over strings? Below is the most minimal reproduction of the issue I can find.

```lisp
;; first, load and use the MaxPC package
(ql:quickload 'maxpc)
(use-package :maxpc)

;; define a MaxPC parser, then use it on a string
(defun =num-string (&optional output special-precedent)
  "Parse a string of text, converting its contents into nested lists of Vex tokens."
  (let ((string-found) (olnchar) (symbols) (is-function-closure)
        (uniform-char) (arg-rooted-path) (fix 0))
    (labels ((?blank-character   () (?satisfies (lambda (char) (member char '(#\  #\Tab)
                                                                       :test #'char=))))
             (?numeric-character () (?satisfies (lambda (char) (or (digit-char-p char)
                                                                   (position char "._¯eEjJrR")))))
             (numeric-string-p (item)
               (loop :for char :across item :always (or (char= #\. char)
                                                        (alphanumericp char)))))
      (=destructure (item _ rest)
          (=list (=transform (%and (?test (#'numeric-string-p)
                                       (=subseq (%some (?numeric-character))))
                                   (=subseq (%some (?numeric-character))))
                             (lambda (string)
                               (print (list :str string))
                               (read-from-string string)))
                 (%any (?blank-character))
                 (=subseq (%any (?satisfies 'characterp))))
        (print (list :it item rest))
        (if (< 0 (length rest))
            (parse rest (=num-string (if output (if (not item) output (cons item output))
                                          (if item (list item)))))
            (list (if (or (not item)
                          (and (typep item 'sequence)
                               (= 0 (length item)) (not string-found)))
                      ;; return nothing if only an empty sequence results from parsing
                      ;; unless an explicit empty string was parsed
                      output (cons item output))
                  rest))))))

(parse "11 22" (=num-string))

#| Printed output:
(:STR "11") 
(:IT 11 "22") 
(:STR "") 
(:IT 22 "") 
|#

;; this should re-implement the portion affected by the bug above
(labels ((?numeric-character () (?satisfies (lambda (char) (or (digit-char-p char)
                                                               (position char "._¯eEjJrR")))))
         (numeric-string-p (item)
           (loop :for char :across item :always (or (char= #\. char)
                                                    (alphanumericp char)))))
    (funcall (%and (?test (#'numeric-string-p)
                     (=subseq (%some (?numeric-character))))
                 (=subseq (%some (?numeric-character))))
           (maxpc.input.vector::make-index-vector :position 0 :vector "22")))

#| Output:
#S(MAXPC.INPUT.VECTOR::INDEX-VECTOR :POSITION 2 :VECTOR "22")
"22"
T
|#
```

The thing to note above is that in the printed output of the `(parse ...)` expression, the second `(:str)` expression contains an empty string. The output of the `(labels ...)` expression has the string `"22"` as its second output value.

The second `(:str)` value should also be `"22"`, and you'll find that it is in other CLs. The `(labels ...)` expression should do the same thing as the `(=transform ...)` section above, but it correctly returns `"22"` as its second value. What I wrote in the `(labels ...)` expression is based on the implementation of MaxPC's `#'=transform` which you can see here: https://github.com/eugeneia/maxpc/blob/master/primitives.lisp#L296. The variable named `string` given to the lambda (second argument to `=transform`) as an argument is populated by the second value returned by the parser function given as the first argument to `=transform`.

This was as far as I could trace the problem, hopefully this is enough for you to find the cause. Let me know if there's any other info that will help.

**Comment by Bike** [comment]
Just to be clear. You're saying that `(parse "11 22" (=num-string))` prints, in Clasp,

```
(:STR "11") 
(:IT 11 "22") 
(:STR "") 
(:IT 22 "") 
```

but it should print

```
(:STR "11") 
(:IT 11 "22") 
(:STR "22")
(:IT 22 "22")
```

Do I have that right?

**Comment by phantomics** [comment]
Yes, that's correct.

**Comment by Bike** [comment]
Reproduced and reduced:

```lisp
(defpackage #:maxpc-break
  (:use #:cl #:maxpc))

(in-package #:maxpc-break)

(defun =num-string ()
  "Parse a string of text, converting its contents into nested lists of Vex tokens."
  (=destructure (item _ rest)
      (=list (=transform (=subseq (%some (maxpc.digit:?digit)))
                         (lambda (string)
                           (print (list :str string))
                           (read-from-string string)))
             (%any (maxpc.char:?whitespace))
             (=subseq (%any (?satisfies 'characterp))))
    (print (list :it item rest))
    (if (< 0 (length rest))
        (parse rest (=num-string))
        nil)))
```

**Comment by Bike** [comment]
This seems to be an issue printing arrays with nested displacement:

```lisp
(let* ((s1 "11 22")
       (s2 (make-array 2 :element-type 'character :displaced-to s1 :displaced-index-offset 3))
       (s3 (make-array 2 :element-type 'character :displaced-to s2)))
  (print s3))
=> ""
```

**Comment by Bike** [comment]
42dbddd fixes the printing problem. But @phantomics, is that the only issue? You said sometimes the parser functions "fail", but in this example the actual parsing seems to have worked fine even before my fix.

(Also, irrelevant sidenote, and sorry for backseat programming: seems like you could replace the complicated `=transform` with `maxpc.digit:=natural-number`?)

**Comment by phantomics** [comment]
Thanks for figuring this out, this example code is a drastically simplified derivative of the lexer from April. In April the `=transform` is needed because when a numeric string is encountered, there is a need to prepend `.` to it in case a `.` was encountered just before the numeric string. See:

https://github.com/phantomics/april/blob/master/vex/vex.lisp#L538

This is because `.` is an operator in APL, but it may also begin a number if you enter a decimal fraction omitting the zero, as with an expression like `1+.5`. So some tricky special cases are needed to handle it.

You're right that parsing returned the right result in my example code, but April was having problems with the `.` prepend case and I guessed that the string problem you found was the root cause, which turned out to be correct. Also, the complicated `%and` form to build the parser is needed because I use a custom function `#'numeric-string-p` to check for valid APL numeric strings, which have a few differences from valid CL numeric strings, such as the ability to contain the letter J for a complex number.

**Comment by Bike** [comment]
So the bug in Clasp is fixed, okay great.
