### ISSUE TITLE
abs of an argument declared fixnum returns a float

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1257]
**Code at issue**

```lisp
(defun abs-fixnum (obj)
  (declare  (fixnum obj))
  (abs obj))

COMMON-LISP-USER>> (abs-fixnum 23)

23.0
````
expected would be 23 as a return value

**Context**
```lisp
(CORE:CLASP-GIT-FULL-COMMIT)
"76aa6b16feb20c855e6d70490bde2fdf60088ee8"
 (clasp-cltl2:declaration-information 'optimize)
((COMPILATION-SPEED 1) (DEBUG 1) (SPACE 1) (SPEED 1) (SAFETY 1))
````

**Comment by Bike** [comment]
https://github.com/clasp-developers/clasp/blob/main/src/lisp/kernel/cleavir/transform.lisp#L323-L327 I stuck `abs` in with the actual irrational functions. That used to be fine, but as of a few days ago they coerce fixnums to single floats. Whoops.
