### ISSUE TITLE
(let ()(endp 1) doesn't signal a type error

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1261]
**Describe the bug**
clhs 14.2.23 says:
````
Exceptional Situations:
Should signal an error of type type-error if list is not a list.
````
**Expected behavior**
`(let ()(endp 1))` should signal `type-error`

**Actual behavior**
`(let ()(endp 1))` returns `nil`

**Comment by kpoeck** [comment]
I believe the compiler-macro for `endp` i incorrect.
`(funcall (compiler-macro-function 'endp) '(endp 1) nil)`
returns 
`(IF (THE LIST 1) NIL T)`

Should the compiler-macro perhaps better be:
```lisp
(define-compiler-macro endp (object)
  `(if (consp ,object) nil
       (if (null ,object)
           t
           (error 'type-error :datum ,object :expected-type 'list))))
````

**Comment by kpoeck** [comment]
so would you agree that
```lisp
(locally
     (declare (optimize (safety 3)))
     (let ()(endp (random 12))))
```

should signal an error?

Would you accept that as a regression test?

**Comment by Bike** [comment]
yes and yes.
