### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [clasp-developers/clasp#1263]
Hey there!

I belong to an open source security research community, and a member (@michaellrowley) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by drmeister** [comment]
Thanks,

I added a SECURITY.md file.

What is the issue?
________________________________
From: Jamie Slome ***@***.***>
Sent: Sunday, February 6, 2022 11:14 PM
To: clasp-developers/clasp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [clasp-developers/clasp] Create SECURITY.md (Issue #1263)


Hey there!

I belong to an open source security research community, and a member ***@***.***<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaellrowley&data=04%7C01%7Cchristian.schafmeister%40temple.edu%7C093a7aaa2d994f07466c08d9e9f061c0%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637798040907859925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8sSUvlfFLmauz%2Bm9TbyW3mKu0xK5boE145DhhwYvvw0%3D&reserved=0>) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a SECURITY.md file with an email, or another contact method? GitHub recommends<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Fcode-security%2Fgetting-started%2Fadding-a-security-policy-to-your-repository&data=04%7C01%7Cchristian.schafmeister%40temple.edu%7C093a7aaa2d994f07466c08d9e9f061c0%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637798040907859925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5RoTvMQDVTfyuiDQeSlFkBMMkl9uWezxVZvreV8CI%2Fo%3D&reserved=0> this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhuntr-helper&data=04%7C01%7Cchristian.schafmeister%40temple.edu%7C093a7aaa2d994f07466c08d9e9f061c0%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637798040907859925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yGJgGB6l8RZf2qDHn5FO6IP7NrTK1rPEOy5n7AJ59Tg%3D&reserved=0>)

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclasp-developers%2Fclasp%2Fissues%2F1263&data=04%7C01%7Cchristian.schafmeister%40temple.edu%7C093a7aaa2d994f07466c08d9e9f061c0%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637798040907859925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zK7nBMDqr8QVuavAl%2BvZq7K0TH9X8GuWp%2Bp0fOKi69c%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABTVUVD5A4WRVPJR2IV2M7DUZ5BLRANCNFSM5NWKZG5Q&data=04%7C01%7Cchristian.schafmeister%40temple.edu%7C093a7aaa2d994f07466c08d9e9f061c0%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637798040907859925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lDril8AWGc%2Bgv3i2%2B5g88F09IkJPI7D21ISaHed7Aaw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristian.schafmeister%40temple.edu%7C093a7aaa2d994f07466c08d9e9f061c0%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637798040907859925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1oFUOi%2FLSqt1rEEXqSxgdyae7ZFCJngrGIuAnZpPFAE%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchristian.schafmeister%40temple.edu%7C093a7aaa2d994f07466c08d9e9f061c0%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637798040907859925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OPMTwZBBiN8xLHEms8RrlYXl0NJemXY%2BKyBzrbSddXM%3D&reserved=0>.

**Comment by JamieSlome** [comment]
@drmeister - appreciate your fast response! ❤️

We will send you an e-mail with a magic URL that will allow you to view the contents of the report without signing up, however, if you want to see the report directly, you can view it here:

https://huntr.dev/bounties/7a92b42b-9323-47ed-888c-2f495e490425/

It is private and only accessible to maintainers with repository write permissions! 👍
