### ISSUE TITLE
Several errors with file-names that are no base-strings

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1288]
**Describe the bug**
all of the following don't work correctly: (segfault, other errors
```lisp
(make-pathname
 :type "lisp"
 :name (concatenate 'string
                    (string #\GREEK_SMALL_LETTER_LAMDA)
                    (string #\GREEK_CAPITAL_LETTER_LAMDA))
 :defaults (user-homedir-pathname))
````
The following is a path from Macos, but will fail on Linux as well
```lisp
(directory
 (make-pathname :name :wild :type :wild :defaults "/System/Library/Fonts/"))
````
```lisp
(let ((name (make-pathname :type "lisp"
               :name (concatenate 'string
                                  (string #\GREEK_SMALL_LETTER_LAMDA)
                                  (string #\GREEK_CAPITAL_LETTER_LAMDA))
                           :defaults (user-homedir-pathname))))
  (when (probe-file name)
    (delete-file name))
  (with-open-file (stream name
                          :direction :output
                          :if-exists :error
                          :if-does-not-exist :create
                          :element-type 'character)
    (format stream "Hello World")))
````
**Expected behavior**
All these examples should work

**Context**
* All of the examples work fine in ecl, but perhaps i was fixed in ecl after the ecl code was converted to c++
* Macos at least seem to expect filenames in a format "utf-8-mac" which fits in a base-string
* ecl seems to do this conversion, see the following comment in pathname.d
```c++
/*
 * si_coerce_to_filename(P) converts P to a physical pathname and then
 * to a properly encoded namestring. The output is a new simple-string
 * or vector of utf-16 characters which can be used by the C library.
 * INV: No wildcards are allowed.
 */
````
* There are utf-8 endecoders in lispStream.cc, see
   * utf_8_decoder
   * utf_8_encoder
* Perhaps they should to be called before any interaction with the os
   * is this also true on Linux/bsd?
* There is a configuration variable CLASP_NAMESTRING_FORCE_BASE_STRING that should control some of that, but perhaps not implemented correctly
* Are `std::string StrWNs_O::get_std_string()` and `std::string SimpleCharacterString_O::get_std_string() ` implemented corretly. 
   * How is an `int` copied into a `char` in `sout[i] = ((*this)[i])`
   * Should that better be `sout[i] = ((*this)[i]) % 256;`

**Comment by kpoeck** [comment]
Will try to solve that, but comments obviously welcome

**Comment by Bike** [comment]
All of these seem to be working in v2.0.
