### ISSUE TITLE
step* is called from top.lisp, but is no longer defined

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1292]
See
https://github.com/clasp-developers/clasp/blob/main/src/lisp/kernel/lsp/top.lisp#L784

Not sure if I can just put `(step)` instead, will try.

`Step*` was deleted in the latest stepper extensions in trace.lisp

**Comment by kpoeck** [comment]
The form in `tpl-step-command`might be already quoted, so this might not work to just put `step` instead of `step*`

**Comment by Bike** [comment]
I did totally remove the old stepper mechanism (or rather, some of the interface around it, since there was no stepper). The new stepper depends on special compilation rather than being an evaluator hook, so nothing like `step*` can be conventionally defined.. I could, I guess, do

```lisp
(defun step* (form)
  (funcall (compile nil `(lambda () (declare (optimize clasp-cleavir::insert-step-conditions)) ,form))))
```

**Comment by drmeister** [comment]
I added Bike's suggestion for step*

```(defun step* (form)
  (funcall (compile nil `(lambda () (step ,form)))))```
