### ISSUE TITLE
handler-case with values and :no-error clause fails

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1297]
**Code at issue**

```lisp
(HANDLER-CASE (values 1 2) (:no-ERROR (X) X))
-> 
; caught ERROR:
;   The assertion (AND (LISTP CLASP-CLEAVIR::MVARGRT)
;                      (= (LENGTH CLASP-CLEAVIR::MVARGRT)
;                         (CLEAVIR-BIR:NVALUES
;                          CLASP-CLEAVIR::INSTRUCTION))) failed
;     at unknown location
; 
; 
; compilation unit aborted
;   caught 1 ERROR condition
(MULTIPLE-VALUE-BIND () (VALUES 1 2 3 4 5))
-> the same
```

**Comment by Bike** [comment]
the primitive issue is with `(multiple-value-call (lambda (x) x) (values 1 2))`

**Comment by hyotang666** [comment]
[CLHS says](http://clhs.lisp.se/Body/m_hand_1.htm)

> (handler-case form
>
>   (type1 (var1) . body1)
>   ...
>   (:no-error (varN-1 varN-2 ...) . bodyN))
>
>is approximately equivalent to:
>
>
> (block #1=#:error-return
>  (multiple-value-call #'(lambda (varN-1 varN-2 ...) . bodyN)
>     (block #2=#:normal-return
>       (return-from #1#
>         (handler-case (return-from #2# form)
>           (type1 (var1) . body1) ...)))))

So I think this is the expected behavior.

**Comment by hyotang666** [comment]
At least sbcl, ccl, ecl, clisp, allegro, cmucl, and abcl do the same behavior. (i.e. signaling the error.)

**Comment by Bike** [comment]
signaling an error when running this code is expected behavior. signaling an internal error while compiling it is not.
