### ISSUE TITLE
Can't load snapshot saved with GCTOOLS:SAVE-LISP-AND-DIE 

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1346]
**Code at issue**

```lisp
build/boehmprecise/iclasp-boehmprecise
(GCTOOLS:SAVE-LISP-AND-DIE "foo-bar.snapshot")
(ext:quit)
build/boehmprecise/iclasp-boehmprecise --image foo-bar.snapshot
->
Hit Segmentation Violation: 000000000000000e#
...
Hit Segmentation Violation: 000000000000000e
zsh: illegal hardware instruction  build/boehmprecise/iclasp-boehmprecise --image foo-bar.snapshot
```

**Context**
* Any other context about the problem
*
works fine with `(GCTOOLS:SAVE-LISP-AND-DIE "foo-bar" :executable t)`

**Comment by Bike** [comment]
I'm not seeing this on 2.0.0.

**Comment by yitzchak** [comment]
Its been fixed on vm for a while

**Comment by Bike** [comment]
In the other issue @oldk1331 reported it as still broken. Are you sure you're using the new version, oldk?

**Comment by Bike** [comment]
I see. Maybe we can arrange to have a more informative error there.

**Comment by yitzchak** [comment]
We don't depend on the extension anymore. Now loading a snapshot is done via `clasp --snapshot <filename>`. Closing.
