### ISSUE TITLE
can't `save-lisp-and-die` twice

### ISSUE THREAD

**Issue by oldk1331** [clasp-developers/clasp#1370]
**Describe the bug**
When using `(gctools:save-lisp-and-die "c1" :executable t)` to dump "c1", then run "c1" with `(gctools:save-lisp-and-die "c2" :executable t)`, it will hang.

**Expected behavior**
Clasp should be able to use `save-lisp-and-die` to dump twice.

**Actual behavior**
Clasp hangs during the second `save-lisp-and-die`.

**Code at issue**

```lisp
(gctools:save-lisp-and-die "c1" :executable t)
;; run following code with "c1"
(gctools:save-lisp-and-die "c2" :executable t)
```

**Comment by Bike** [comment]
sorry for the tag noise, i misunderstood your report.

**Comment by drmeister** [comment]
There was still an issue with object files being consumed by the LLVM JIT when a snapshot was loaded and this would prevent snapshot-save from working after that.  I fixed this problem today.
