### ISSUE TITLE
Crashes where no other implementation does

### ISSUE THREAD

**Issue by q3cpma** [clasp-developers/clasp#1371]
**Describe the bug**
When running the `NBody` benchmark from https://github.com/q3cpma/are-we-fast-yet/tree/common-lisp/benchmarks/Common-Lisp I get a strange error `NIL is not of type DOUBLE-FLOAT` in the `energy` method (full [backtrace](https://github.com/clasp-developers/clasp/files/9685586/NBody-opt_clasp_backtrace.txt) attached) that I can't easily reproduce without calling it through `harness.lisp`.

I tried to rip the part doing the dynamic loading, symbol finding and funcall from `harness.lisp` (L16-22), but it didn't crash anymore.

**Expected behavior**
```
$ git clone https://github.com/q3cpma/are-we-fast-yet/tree/common-lisp
$ cd are-we-fast-yet/benchmarks/Common-Lisp/
$ clasp --script harness.lisp -- NBody 1 1
Starting "nbody" benchmark ...
"nbody": iterations=1 runtime: 5000.us
"nbody": iterations=1 average: 5000.us total: 5000.us

Total Runtime: 5000.us
```
Works with SBCL, CCL, CLISP and ECL.

**Code at issue**
Too big to paste, see **Expected behavior** section.

**Context**
* Built today.
* If relevant, your operating system and other aspects of your computing environment
* `harness.lisp` contains a `(declaim (optimize (debug 0) (safety 0) (speed 3)))`

**Comment by yitzchak** [comment]
This could very well be an actual bug in Clasp, but it is hard to know with a simple reproducer. I was able avoid the issue by removing all of the `:type double-float` from your structure definition. 

There seems to be a lot of type issues in your code. You are declaring variables and slots to be double floats but the literals are often single floats. I didn't look any closer than a casual inspection though.

Also, you could use `SUM` to simplify your energy method.

```lisp
(defmethod energy ((self nbody-system))
  (loop for i-body across (bodies self)
        for i from 0
        sum (* 0.5d0
               (mass i-body)
               (+ (expt (vx i-body) 2)
                  (expt (vy i-body) 2)
                  (expt (vz i-body) 2)))
        sum (loop for j-body across (bodies self)
                  for j from 0 below i
                  sum (/ (- (* (mass i-body) (mass j-body)))
                         (sqrt (+ (expt (- (x i-body) (x j-body)) 2)
                                  (expt (- (y i-body) (y j-body)) 2)
                                  (expt (- (z i-body) (z j-body)) 2)))))))
```

**Comment by q3cpma** [comment]
Look at the top, I've set the default float read format.


-------- Courriel d’origine --------
De : "Tarn W. Burton" ***@***.***>
Envoyé : 2 octobre 2022 22:41:05 CEST
À : clasp-developers/clasp ***@***.***>
Cc : q3cpma ***@***.***>, Author ***@***.***>
Objet : Re: [clasp-developers/clasp] Crashes where no other implementation does (Issue #1371)

This could very well be an actual bug in Clasp, but it is hard to know with a simple reproducer. I was able avoid the issue by removing all of the `:type double-float` from your structure definition. 

There seems to be a lot of type issues in your code. You are declaring variables and slots to be double floats but the literals are often single floats. I didn't look any closer than a casual inspection though.

Also, you could use `SUM` to simplify your energy method.

```lisp
(defmethod energy ((self nbody-system))
  (loop for i-body across (bodies self)
        for i from 0
        sum (* 0.5d0
               (mass i-body)
               (+ (expt (vx i-body) 2)
                  (expt (vy i-body) 2)
                  (expt (vz i-body) 2)))
        sum (loop for j-body across (bodies self)
                  for j from 0 below i
                  sum (/ (- (* (mass i-body) (mass j-body)))
                         (sqrt (+ (expt (- (x i-body) (x j-body)) 2)
                                  (expt (- (y i-body) (y j-body)) 2)
                                  (expt (- (z i-body) (z j-body)) 2)))))))
```



-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Bike** [comment]
Assuming this code was moved to nbody.lisp. I can reproduce the error as long as I have that proclamation.

**Comment by q3cpma** [comment]
Thanks for trying, I've amended the OP to make it easy to reproduce anew.

**Comment by Bike** [comment]
reduction

```lisp
(defun test (s)
  (declare (double-float s) (optimize (safety 0)))
  (let ((dx nil))
    (setq dx (- s s))
    (* dx dx)))
(test 3d0) ; or some other double
```

The problem is that due to the declared types of the structs, Clasp infers that dx is a double and tries to keep it unboxed. The compiler (internals jargon incoming) figures the rtype as being `:double-float`, which is all well and good, except that `loop` has an implicit binding of `nil`; the compiler inserts a cast from `:object` to `:double-float`, and the casts are checked even in unsafe code, so when it gets `nil` it throws up an error. Not totally sure why this goes away on higher safety, but meh.

I'll have to think about the best way to solve this. Ideally the initial binding would be deleted, but that could be unreliable. Casts should be delayed a bit more, I guess?

**Comment by q3cpma** [comment]
Thanks for your work, I doubt I would have found the loop interaction easily.

**Comment by Bike** [comment]
I am, for better or worse, an old hand at muntzing compiler bugs. Anyway, I think I have a fix, which I will try out now. It will unfortunately degrade the optimizer. I'll need to put in some code to delete unused variable definitions. Should overhaul representation selection also.

**Comment by Bike** [comment]
With that commit, I can make my reduced example work, as well as nbody.lisp modified to avoid external references. I have not tried it in the benchmark harness.

**Comment by Bike** [comment]
So, slowness aside, is this bug resolved?

**Comment by q3cpma** [comment]
Yes.
