### ISSUE TITLE
Cannot change readtable while compiling files

### ISSUE THREAD

**Issue by bohonghuang** [clasp-developers/clasp#1398]
**Describe the bug**
`*readtable*` cannot be changed during file compilation.

**Expected behavior**
Once `(setf *readtable* ...)` is evaluated by the compiler, the changed readtable should affect the rest of the file like other implementations do.

**Code at issue**
Eval `(ql:quickload :trivia.quasiquote)` and compile a file that contains this:

```lisp
(named-readtables:in-readtable :fare-quasiquote) ;; Expands to (eval-when (:compile-toplevel :load-toplevel :execute) (setf *readtable* ...

(eval-when (:compile-toplevel :load-toplevel :execute)
  (assert (eq (car ``A) 'fare-quasiquote::quote)))
```
The assertion will fail during compilation.

**Context**
* Clasp Version: 2.0.0

**Comment by Bike** [comment]
This appears to be because we use Eclector, which has its own readtable variable. We bind it to `*readtable*` before compiling, but further modifications will be ignored. I guess we'll have to identify the variables somehow.

**Comment by yitzchak** [comment]
I've been thinking this because it is related to some of the client dispatch issues I am working through with Incless + Invravina.  One solution would be if Eclector had client dispatched access to the current readtable.

```lisp
(in-package #:eclector.reader)

(defgeneric readtable (client)
  (:method (client)
    (declare (ignore client))
    *readtable*))

(defgeneric (setf readtable) (new-value client)
  (:method (new-value client)
    (declare (ignore client))
    (setf *readtable* new-value)))
```

Then we could do 

```lisp
(defmethod eclector.reader:readtable ((client clasp-non-cst-elector-client))
  cl:*readtable*)

(defgeneric (setf eclector.reader:readtable) (new-value (client clasp-non-cst-elector-client))
  (setf cl:*readtable* new-value))
```

I don't see anywhere in the eclector.reader sources new dynamic bindings being introduced for `*readtable*`. That would require some kind of CALL-WITH-READTABLE generic.

**Comment by Bike** [comment]
That solution sounds good to me. I would guess that Eclector doesn't rebind `*readtable*` any more than the standard reader does, so `call-with-readtable` may be extraneous.

I just dropped a note for @scymtym about this issue on IRC. Maybe this can be rolled into the upcoming Eclector version.

**Comment by yitzchak** [comment]
Can you give a little more detail? It seemed fine on my system.

**Comment by bohonghuang** [comment]
> Can you give us a little more detail? It seemed fine on my system.

 I built and installed Clasp via AUR:

``` shell
$ pacman -Q clasp-cl
clasp-cl 2.3.0-1
$ clasp
Starting clasp-boehmprecise-2.2.0 from base image
Loading resource file /home/coco24/.clasprc
Top level in: #<PROCESS TOP-LEVEL @0x7f35d2e7ff09 (Running)>.
COMMON-LISP-USER> (compile-file #P"test.lisp")
; Compiling file: test.lisp
To load "fare-quasiquote-readtable":
  Load 1 ASDF system:
    fare-quasiquote-readtable
; Loading "fare-quasiquote-readtable"

;   (EVAL-WHEN (:COMPILE-TOPLEVEL :LOAD-TOPLEVEL ...) ...)
;   (EDITOR-HINTS.NAMED-READTABLES:IN-READTABLE :FARE-QUASIQUOTE)
; caught ERROR:
;   ERROR while evaluating compiler-time side effect:
;     The assertion (EQ (CAR ``A) 'FARE-QUASIQUOTE::QUOTE) failed
;     at /tmp/test.lisp 7:2
; 

Condition of type: EVAL-ERROR
ERROR while evaluating compiler-time side effect:
  The assertion (EQ (CAR ``A) 'FARE-QUASIQUOTE::QUOTE) failed
Available restarts:
(use :r1 to invoke restart 1, etc.)

1. (SIGNAL-ORIGINAL-CONDITION) Let the originally signaled condition propagate.
2. (CONTINUE) Replace with call to ERROR.
3. (SUBSTITUTE-CST) Compile the given CST in place of the problematic one.
4. (CONTINUE) Replace with call to ERROR.
5. (SUBSTITUTE-CST) Compile the given CST in place of the problematic one.
6. (CONTINUE) Replace with call to ERROR.
7. (SUBSTITUTE-CST) Compile the given CST in place of the problematic one.
8. (CONTINUE) Replace with call to ERROR.
9. (SUBSTITUTE-CST) Compile the given CST in place of the problematic one.
10. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

((LAMBDA (CONDITION)) #<EXT:ASSERT-ERROR @0x7f35b296fa89>)
COMMON-LISP-USER>> 
```

Here is the content of `test.lisp`:

``` lisp
(eval-when (:compile-toplevel :load-toplevel :execute)
  (ql:quickload :fare-quasiquote-readtable))

(named-readtables:in-readtable :fare-quasiquote)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (assert (eq (car ``A) 'fare-quasiquote::quote)))
```

**Comment by yitzchak** [comment]
Looks like we need the Eclector state-value methods for the cst client also. Opened a PR with the fix.
