### ISSUE TITLE
MacOS build can't find llvm-config

### ISSUE THREAD

**Issue by slyrus** [clasp-developers/clasp#1453]
I'm probably doing something wrong but trying to follow the build instructions, I get the following error:

```
Configuring the build
Configuring git
Found git program with path git 
Updating version number.
Set version number to 2.2.0-114-g4f6d36d50
Inspecting system to determine the number of cpu cores
Found 8 cpu cores. Setting the number of jobs to 10.
Configuring XCode SDK
Configuring base
Configuring the default target
Configuring pkg-config
Found pkg-config program with path pkg-config 
Configuring LLVM
Unable to find llvm-config program compatible with major version 15.
```

But llvm 15 is installed. Do I need to do something to install llvm-config?

```
sly@girona clasp % brew search llvm
brew search llvm
==> Formulae
cargo-llvm-lines           llvm@12                    llvm@15 ✔                  llvm@9
llvm                       llvm@13                    llvm@7                     spirv-llvm-translator
llvm@11                    llvm@14                    llvm@8                     wllvm
sly@girona clasp % 
```

**Comment by slyrus** [comment]
Adding the following:

```
export PATH="/opt/homebrew/opt/llvm@15/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/llvm@15/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm@15/include"
```

fixes things, FWIW.

**Comment by yitzchak** [comment]
You can avoid the LDFLAGS by using the `--llvm-config` option of koga to specify the path to llvm-config. You can also also make a config.sexp file with `(:llvm-config #P"path-to-llvm-config")`. koga tries to auto detect the path for you and the options are the backup. I'll look into adding that homebrew path to the search logic.

**Comment by yitzchak** [comment]
I added the additional path to the search list if you want to try again.

**Comment by yitzchak** [comment]
@slyrus I'm closing this as resolved. If there is a problem please let me know and I'll reopen. Also, we have prepackaged homebrew builds if that is more convient. https://github.com/clasp-developers/homebrew-clasp/
