### ISSUE TITLE
Latest release (2.2.0) doesn't build any more.

### ISSUE THREAD

**Issue by m-e-leypold** [clasp-developers/clasp#1460]
**Describe the bug**
Trying to build (on arch linux), when invoking koga, it tries to download https://gitlab.common-lisp.net/yitzchak/ansi-test, a repository that does not exist any more (or has been made private). 

I know this has been fixed on main, but there has been no release yet.

**Expected behavior**
- That the latest release always builds.
- Actually I would expect the release tarball to be reasonably self contained, that is, can be build on a machine without network connection after sufficient packages have been installed there. I understand I might be too radical with that expectation, but I thought this would be a good opportunity to point out that "downloading during build from a release tarball" might considered unexpected.

**Actual behavior**
- See above.

**Code at issue**
./koga

**Other steps to reproduce**
- Download the 2.2.0 tarball from https://github.com/clasp-developers/clasp/releases/tag/2.2.0
- Unpack.
- cd into it
- call ./koga

**Context**
None further

**Comment by yitzchak** [comment]
I'll release a v2.3.0 this week to fix this.

**Comment by yitzchak** [comment]
v2.3.0 has been released
