### ISSUE TITLE
The version number has not been updated to 2.3.0

### ISSUE THREAD

**Issue by bohonghuang** [clasp-developers/clasp#1462]
**Describe the bug**
On version 2.3.0, the version number is still `"cclasp-boehmprecise-2.2.0-cst"`, which causes the compiler to use the compilation cache of the previous version, resulting in some strange errors.

**Expected behavior**
``` lisp
(lisp-implementation-version) ; => "cclasp-boehmprecise-2.3.0-cst"
```

**Actual behavior**
``` lisp
(lisp-implementation-version) ; => "cclasp-boehmprecise-2.2.0-cst"
```

**Context**
* Clasp Version: 2.3.0

**Comment by yitzchak** [comment]
I forgot to update the version file. I've updated it but it won't fix the tag without rebasing. We'll just catch it in the next version.
