### ISSUE TITLE
Additional Command Line Options

### ISSUE THREAD

**Issue by Shinmera** [clasp-developers/clasp#150]
The following options would be very useful to have for clasp:

* [x]  ``--help                     Print this message and exit.``
* [x]  ``--version                  Print version information and exit.``
* [x]  ``--userinit <filename>      Per-user init-file to use instead of default.``
* [x]  ``--no-userinit              Inhibit processing of any per-user init-file.``
* [x]  ``--disable-debugger         When an unhandled error occurs, simply exit (with stack trace printed).``
* [x]  ``--noprint                  Run a Read-Eval Loop without printing results.``
* [ ]  ``--script [<filename>]      Skip #! line, disable debugger, avoid verbosity.``
* [x]  ``--quit                     Exit with code 0 after option processing.``
* [x]  ``--non-interactive          Sets both --quit and --disable-debugger.``
* [x]  ``--eval <form>              Form to eval when processing this option.``
* [x]  ``--load <filename>          File to load when processing this option.``

Taken from the SBCL options.

**Comment by Bike** [comment]
By now we support `--help`, `--version`, `--no-userinit` (as `-r` or `--norc`), `--non-interactive`, `--eval`, `--load`.

**Comment by Shinmera** [comment]
Okey, turned the list into a checkbox thingie, so just check off as things get added.

**Comment by Bike** [comment]
Added `--disable-debugger`. It has slightly different semantics from SBCL, in that it only affects the default debugger. Like, if you have your own `*(invoke-)debugger-hook*`, it's still run as usual.

**Comment by Bike** [comment]
yitzi points out that we have `--userinit`` as `--rc`

**Comment by yitzchak** [comment]
I've triaged `--script` so I can take care of that.
