### ISSUE TITLE
Build/Installation failing to find fmt (module/package?)

### ISSUE THREAD

**Issue by rkazak** [clasp-developers/clasp#1630]
**Describe the bug**
When installing/building clasp I get the following error.
```
...
Found script src/cscript.lisp
Configuring library fmt
Module fmt not found.
```

**Expected behavior**
installation/build to succeed.

**Actual behavior**
See attached - [clasp-install.log](https://github.com/user-attachments/files/16913142/clasp-install.log)

**Other steps to reproduce**
Follow the 

**Context**
- Using the latest zip file.
- Intel OSX 14.6.1

**Comment by yitzchak** [comment]
You need to have fmtlib installed. Koga uses pkgconfig to find it so you can do `pkg-config fmt --modversion` to verify that it is around.

**Comment by rkazak** [comment]
Thank you. Found the required package under brew.

**Comment by rkazak** [comment]
resolved.

**Comment by yitzchak** [comment]
Awesome!
