### ISSUE TITLE
Cannot build outside of version control (0.4.0)

### ISSUE THREAD

**Issue by drjdn** [clasp-developers/clasp#175]
I think there is missing git information in the tar.gz of the recent release (congrats on the new release).  I get messages like the following:

fatal: Not a git repository (or any parent up to mount point

If I clone from master everything builds fine and the proper submodules are pulled.

Best regards,
Jason

**Comment by Georgiy-Tugai** [comment]
This is a known issue with using `git describe` and friends for version detection; thanks for reminding us about this, though :+1:

**Comment by Shinmera** [comment]
Gergh, and here I thought I had worked around that problem in the makefile.

**Comment by Georgiy-Tugai** [comment]
@Shinmera Is there any procedure for releases at the moment other than "click the release button on github"?

**Comment by Georgiy-Tugai** [comment]
Title changed since version info is the least of our problems here. Submodules are pulled in by the Makefile, and Github's tarballs include empty directories where submodules are meant to be.
