### ISSUE TITLE
Rearrange string code to support displaced strings and prepare for Unicode

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#179]
Currently only 8bit-character strings are supported.  Code needs to be moved out of str.cc into lispString.cc and generalized somewhat to support new types of strings like 16 bit character, and Unicode.

There is also a bug that there is no displaced string type and so (make-array 2 :element-type 'character :displaced-to "abcdefg")   doesn't work -

**Comment by dkochmanski** [comment]
As a temporary issue you may make character being the same type as base-char (ECL does that for builds without unicode) – this would fix this error

**Comment by Shinmera** [comment]
I think that's already the case.

**Comment by kpoeck** [comment]
(make-array 2 :element-type 'base-char :displaced-to "abcdefg") -> "ab"

**Comment by Bike** [comment]
we now have displaced arrays and at least in large part have unicode strings, so I'm going to close this. Further unicode issues can be thrown in to #164
