### ISSUE TITLE
Convert &rest using functions to two-arg functions

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#204]
- [x] logand
- [x] logior
- [x] logxor
- [x] logeqv
- [x] /
- [x] min
- [x] max
- [x] char=
- [ ] char-equal
- [ ] char/=
- [ ] char-not-equal
- [ ] char<
- [ ] char<=
- [ ] char>
- [ ] char>=
- [ ] char-lessp
- [ ] char-not-greaterp
- [ ] char-greaterp
- [ ] char-not-lessp

[Bike edit: rewrote as checklist]

[Bike edit two: added char< etc]

**Comment by Bike** [comment]
`/`, `char=`, `max`, `min` are done. `char/=` and `char-not-equal` are tricky because they involve a quadratic number of comparisons. `logand` and `char-equal` remain.

**Comment by kpoeck** [comment]
If have logand, logior, logxor, logeqv fixed locally (with a compiler-macro using Bikes work)
Will look for char-equal

**Comment by Bike** [comment]
kpoeck added those in PR #828

**Comment by Bike** [comment]
Also b2279a365b8f17c0336e178dae7712da1c424fa0 which takes care of `char<` and such.

That covers everything in the original issue and then some. We can reopen this if we find more.
