### ISSUE TITLE
find-symbol conses

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#214]
Because it is using Str_sp s = Str_O::create(name)  ---- why?

**Comment by drmeister** [comment]
15:50 <stassats> so, should it be not cl__find_symbol(const string &symbolname 
15:50 <stassats> but cl__find_symbol(T_sp string symbolname)?
15:51 <stassats> s/string//
15:51 <stassats> or even Str_sp

**Comment by Bike** [comment]
In b83afab, cl__find_symbol does not call create directly; it calls coerce::packageDesignator, coerce::simple_string, and then package::findSymbol_SimpleString. coerce::simple_string does call make, but only if it receives a character. Similar with packageDesignator, and findSymbol_SimpleString calls ditto_no_lock which doesn't seem to allocate anything at all. So I don't think this will cons any more, but I'm not sure how to test that rigorously.

**Comment by Bike** [comment]
Probably fine.
