### ISSUE TITLE
Convert (if (not x) 1 2) into (if x 2 1)

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#252]

**Comment by kcousins** [comment]
Shouldn't this be "Convert (if (not x) 1 2) into (if x **2 1**)?

What am I not understanding?

**Comment by Shinmera** [comment]
You are correct. @drmeister was a bit too hasty typing in the title.

**Comment by Shinmera** [comment]
How would I go about testing this?

**Comment by Bike** [comment]
This is covered by karlosz's improvements in Cleavir over the last year or so. Mostly the if-if elimination in meta-evaluate https://github.com/s-expressionists/Cleavir/blob/cc165204b3c13b14d65abe64c20f94c8116a0d99/BIR-transformations/meta-evaluate.lisp#L186-L225 in concert with the compiler macro that rewrites `not` calls as `if` forms https://github.com/clasp-developers/clasp/blob/45ab39da2d0354939d25526b2b71a633977cb196/src/lisp/kernel/cmp/opt-control.lsp#L36
