### ISSUE TITLE
Provide source-info for C++ methods.

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#263]
The data is scraped and available in the generated/sourceInfo_inc.h file but it's not yet provided by ext:compiled-function-file or provided to slime for M-. to work on C++ methods.
What needs to be done:
(1) in gc_interface.cc>define_source_info for method_kind the source info for each method needs to be appended to a list and stored in sysprops under 'core:method-source-info.  The source files are relative to SOURCE-DIR:
(2) In compiled-function-file the source info needs to be retrieved from sysprops (see (1)) and the absolute pathname needs to be generated relative to SOURCE-DIR: for each entry.
(3) The swank clasp.lisp>source-location function needs to be modified to retrieve the results of compiled-function-file and return it to slime.   It's going to be a list - but the source-location function doesn't look like it can handle a list - talk to Stas about it.

**Comment by Bike** [comment]
We've had this for a while actually.
