### ISSUE TITLE
Macro source-locations offsets don't point to the right place

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#270]
They need to point to the start of the macro.

They also shouldn't be returned by (ext:source-location 'shiftf :function).
They need their own :macro kind.

**Comment by Bike** [comment]
Seems to be the correct position for me, but `source-location` does indeed not care.

**Comment by Bike** [comment]
I don't think we need a separate macro kind. As is we match, like, `documentation`. So we're fine here.
