### ISSUE TITLE
(ext:source-location #'clos::generic-function-lambda-list t) => (#S(SOURCE-LOCATION :PATHNAME #P"-unknown-file-" :OFFSET 0))

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#273]
It shouldn't return a useless struct like this.

**Comment by drmeister** [comment]
two points a) it should record "-unknown-file-" if it can't determine the file b) it should determine it in this case
14:04 (ext:source-location (defun foo ()) :function) => (#S(SOURCE-LOCATION :PATHNAME #P"repl-code" :OFFSET 0))
14:04 same point here

**Comment by Bike** [comment]
This is kind of vague, so I'm closing it. #539 covers bad accessor info and #288 is for better source tracking generally.
