### ISSUE TITLE
RANDOM doesn't work on bignums

### ISSUE THREAD

**Issue by stassats** [clasp-developers/clasp#293]

**Comment by drmeister** [comment]
From a discussion on #clasp stassats recommended switching to using the GMP library to generate random numbers.   It has functions to generate integer and float random numbers.  A bonus would be that switching to GMP would eliminate the boost::random library as a dependency.

**Comment by Bike** [comment]
seems to work (e.g. `(random (* 2 most-positive-fixnum))`) as of 697b2cf

**Comment by stassats** [comment]
(random (expt 2 1280)) crashes.

**Comment by Bike** [comment]
"floating point exception: 8"

that's weird. it looked like random was hooked up to mpz

**Comment by kpoeck** [comment]
(random (expt 2 1026)) seems to work
(random (expt 2 1027)) -->
Floating point exception: 8

**Comment by Bike** [comment]
Seems to be working again.

**Comment by kpoeck** [comment]
works for me, would close
