### ISSUE TITLE
The compiler shouldn't allow (defun foo () (not 1 2 3))

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#302]
NOT only takes one argument.

**Comment by drmeister** [comment]
NOT only takes one argument.

**Comment by Bike** [comment]
The basic code is already there in Cleavir - https://github.com/robert-strandh/SICL/blob/2a14ded81bb8a4e8b399d6573bc7b16553258e6c/Code/Cleavir/Generate-AST/convert-form.lisp#L305-L310

I asked @robert-strandh how he wanted compiler warnings and such to be done and he hasn't got a protocol together yet. But once there's a system, all that has to happen is a little edit at that point.

**Comment by Bike** [comment]
At this point the problem is that clasp does not have type or ftype information for global functions. This is how Cleavir knows that `not` only takes one argument.

**Comment by kpoeck** [comment]
COMMON-LISP-USER> (defun foo () (not 1 2 3)) 
;;; Warning: NOT was called with too many arguments:
(NOT 1 2 3)
Expected at most 0, as inferred from its inline definition.

at most 0 seems kind of strange

**Comment by kpoeck** [comment]
```lisp
Condition of type: SIMPLE-ERROR
Too many arguments supplied to a macro or a destructuring-bind form:
(NOT 1 2 3)

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
````

i' claim this is good enough
