### ISSUE TITLE
Division By Zero Causes a Floating Point Exception (Hard Crash)

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#305]
I doubt this is unknown (e.g. #104) but it seems pretty important?

```
Starting Boehm cclasp b'0.4.0-1094-gc89cde5' ... loading image... it takes a few seconds
Top level.
> (/ 1 0)
floating point exception (core dumped)
```

or

```
> (exp 2000e0)
floating point exception (core dumped)
```

**Comment by Shinmera** [comment]
We discovered that some days ago but I guess I forgot to file a ticket.

The strange thing about it is that it signals an FPE on division by zero regardless of what the actual number types are.

**Comment by Bike** [comment]
overflow also seems to do it. i couldn't trigger an underflow and i don't remember enough about things to get an inexact.

**Comment by Shinmera** [comment]
That should be a separate issue though, since this error is unique in that it happens regardless of the number type.

**Comment by kpoeck** [comment]
COMMON-LISP-USER> (/ 1 0)
Condition of type: DIVISION-BY-ZERO
#<DIVISION-BY-ZERO>
