### ISSUE TITLE
Can't sqrt ratios or bignums

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#306]
```
> (sqrt 1/2)
File(../../include/clasp/core/numbers.h) lineNumber(188): Subclass[RATIO] must implement method[sqrt_]
```

I don't understand the C++ side of things very well, but perhaps this could be fixed by adding a definition (in numbers.cc) analogous to the one for sin? Though with extra handling for negatives.

**Comment by Bike** [comment]
This affects bignums as well: (sqrt (1+ most-positive-fixnum)) => same error but with subclass[BIGNUM]

I see a clasp_sqrt function that checks for fixnums and takes the sqrt of the float. Maybe that just needs to be expanded to rationals.

**Comment by kpoeck** [comment]
For Bignum I think I have a proposal in #387 
For Ratio I think the following has to be done:
In numbers.h declare in class Ratio_O : public Rational_O {
...
Ratio_sp sqrt_() const;
....
}

and in Numbers.cc

**Comment by kpoeck** [comment]
```
Number_sp Ratio_O::sqrt_() const {
        // (sqrt (/ x y) == (/ (sqrt x) (sqrt y)
    return Ratio_O::create(clasp_sqrt(this->_numerator), clasp_sqrt(this->_denominator));
}
```
Does not work totally, since I get 
(sqrt (/ 9 16))

Debugger received error of type: SIMPLE-TYPE-ERROR
In function clasp_gcd, the value of the first argument is
  3.0
which is not of the expected type INTEGER

Need to round to Integer somehow, will investigate (any help obviously appreciated)

**Comment by Bike** [comment]
shouldn't bother trying to return a rational, we can do that later if we want to

**Comment by kpoeck** [comment]
second try, works better with (sqrt (/ 2 3))
Please review

in numbers.h
```
class Ratio_O : public Rational_O {
....
Number_sp sqrt_() const;
....
}

```
in numbers.cc
```
Number_sp Ratio_O::sqrt_() const {
    // (sqrt (/ x y) == (/ (sqrt x) (sqrt y)
    return clasp_divide(clasp_sqrt(this->_numerator), clasp_sqrt(this->_denominator));
}
```

**Comment by kpoeck** [comment]
(sqrt 1/2) works
(sqrt (1+ most-positive-fixnum))
works
Probably could be closed?
