### ISSUE TITLE
Floating Point Exceptions Crash Clasp

### ISSUE THREAD

**Issue by Shinmera** [clasp-developers/clasp#307]
If an FPE occurs such as division by zero, overflow, underflow, inexact, Clasp simply crashes with a core dump. Not exactly a very lispy experience.

**Comment by kpoeck** [comment]
Still happening:
karsten-poecks-macbook-pro:ansi-cl-tests karstenpoeck$ ~/lisp/compiler/clasp/build/boehm/cclasp-boehm
Starting Boehm cclasp FRGO_CLASP_DEV_FOREIGN_DATA_002-1990-gc9f423501 ... loading image... it takes a few seconds
Top level in: #<PROCESS TOP-LEVEL @0x1106c6e7f>.
COMMON-LISP-USER> (/ 3 0)          
Floating point exception: 8

**Comment by kpoeck** [comment]
```lisp
COMMON-LISP-USER> (/ 3 0)
Condition of type: DIVISION-BY-ZERO
#<DIVISION-BY-ZERO>
````

Does handle at least the example here ok
