### ISSUE TITLE
A whole slew of array issues

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#325]
```
;;write-to-string is broken on #\Nul
(substitute #\a #\Nul  (prin1-to-string (make-string 3 :initial-element #\Nul))) => "\"aaaa"
;;all characters after #\Nul in the string-output-stream turn into #\Nul
(substitute #\X #\Nul (with-output-to-string (str) (write-char #\Nul str) (princ "123" str))) => "XXXX"
(concatenate 'string (make-string 3 :initial-element #\Nul) "abc") => "abc"
(copy-seq (concatenate 'string (make-string 3 :initial-element #\Nul) "abc")) => ""
(make-array '(1 1) :element-type 'bit) => #2A((NIL))
;;that's kinda wrong
;;or
(make-array '(1 1) :element-type 'character) => #2A((NIL))
(aref #2A((1) (2)) 0) => 1
(aref #2A((1) (2)) 0 1)
;;--> ../../src/main/main.cc:109  The generic catch(...) caught an unhandled exception of type 0x3e5fb80 - fix this!!!!
(aref #2A((1) (2)) 0 0 0 0 0) => 1
;;or
(aref #2A((1) (2))) => 1
(row-major-aref #2A((1) (2)) 10) => T
(row-major-aref "ab" 10) => #\NUL
```

**Comment by drmeister** [comment]
I'm working on arrays - hopefully the new code will resolve some or all of these.

**Comment by drmeister** [comment]
These are special ones that I'm not are wrong - sbcl generates similar results:
(make-array '(1 1) :element-type 'bit) => #2A((NIL))
;;that's kinda wrong
;;or
(make-array '(1 1) :element-type 'character) => #2A((NIL))

**Comment by drmeister** [comment]
These are fixed and regression tests were created.
;;write-to-string is broken on #\Nul
(substitute #\a #\Nul  (prin1-to-string (make-string 3 :initial-element #\Nul))) => "\"aaaa"
;;all characters after #\Nul in the string-output-stream turn into #\Nul
(substitute #\X #\Nul (with-output-to-string (str) (write-char #\Nul str) (princ "123" str))) => "XXXX"
(concatenate 'string (make-string 3 :initial-element #\Nul) "abc") => "abc"
(copy-seq (concatenate 'string (make-string 3 :initial-element #\Nul) "abc")) => ""

**Comment by drmeister** [comment]
The other ones are safety and bounds checking issues that I would like to revisit once the compiler can work for us to do safety checks.
```
(aref #2A((1) (2)) 0) => 1
(aref #2A((1) (2)) 0 1)
;;--> ../../src/main/main.cc:109  The generic catch(...) caught an unhandled exception of type 0x3e5fb80 - fix this!!!!
(aref #2A((1) (2)) 0 0 0 0 0) => 1
;;or
(aref #2A((1) (2))) => 1
(row-major-aref #2A((1) (2)) 10) => T
(row-major-aref "ab" 10) => #\NUL
```

**Comment by Bike** [comment]
We do need actual full calls to these functions to do bounds checking. It's not all on the compiler.

**Comment by kpoeck** [comment]
The errors from the last comment from drmeister are all fixed
