### ISSUE TITLE
trivial-gray-streams-test  fails two tests

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#339]
(load "~/quicklisp/setup.lisp")
(ql:quickload :trivial-gray-streams-test)
CANDO-USER>  (asdf:test-system "trivial-gray-streams")
T
CANDO-USER> (trivial-gray-streams-test:run-tests)
Running test GRAY:STREAM-READ-CHAR... OK
Running test GRAY:STREAM-UNREAD-CHAR... OK
Running test GRAY:STREAM-READ-CHAR-NO-HANG... OK
Running test GRAY:STREAM-PEEK-CHAR... OK
Running test GRAY:STREAM-LISTEN... OK
Running test GRAY::STREAM-READ-LINE... FAIL: Unexpected end of file on #<TRIVIAL-GRAY-STREAMS-TEST::TEST-STREAM>.
Running test GRAY:STREAM-CLEAR-INPUT... OK
Running test GRAY:STREAM-WRITE-CHAR... OK
Running test GRAY:STREAM-LINE-COLUMN... OK
Running test GRAY::STREAM-START-LINE-P... OK
Running test GRAY:STREAM-WRITE-STRING... OK
Running test GRAY:STREAM-TERPRI... OK
Running test GRAY:STREAM-FRESH-LINE... OK
Running test GRAY:STREAM-FINISH-OUTPUT... OK
Running test GRAY:STREAM-FORCE-OUTPUT... OK
Running test GRAY:STREAM-CLEAR-OUTPUT... OK
Running test GRAY:STREAM-ADVANCE-TO-COLUMN... FAIL: expected invocation: (gray:stream-advance-to-column #<trivial-gray-streams-test::test-stream2> 10) actual: (gray:stream-line-column #<trivial-gray-streams-test::test-stream2>), (gray:stream-write-string #<trivial-gray-streams-test::test-stream2>
                          "                                                                                                    "
                          0
                          10)
Running test GRAY:STREAM-READ-BYTE... OK
Running test GRAY:STREAM-WRITE-BYTE... OK
Running test TRIVIAL-GRAY-STREAMS:STREAM-READ-SEQUENCE... OK
Running test TRIVIAL-GRAY-STREAMS:STREAM-WRITE-SEQUENCE... OK
Running test TRIVIAL-GRAY-STREAMS:STREAM-FILE-POSITION... OK
Running test TRIVIAL-GRAY-STREAMS-TEST::SETF-STREAM-FILE-POSITION... OK

**Comment by kpoeck** [comment]
now:
```lisp
COMMON-LISP-USER> (trivial-gray-streams-test:run-tests)
Running test GRAY:STREAM-READ-CHAR... OK
Running test GRAY:STREAM-UNREAD-CHAR... OK
Running test GRAY:STREAM-READ-CHAR-NO-HANG... OK
Running test GRAY:STREAM-PEEK-CHAR... OK
Running test GRAY:STREAM-LISTEN... OK
Running test GRAY:STREAM-READ-LINE... OK
Running test GRAY:STREAM-CLEAR-INPUT... OK
Running test GRAY:STREAM-WRITE-CHAR... OK
Running test GRAY:STREAM-LINE-COLUMN... OK
Running test GRAY::STREAM-START-LINE-P... OK
Running test GRAY:STREAM-WRITE-STRING... OK
Running test GRAY:STREAM-TERPRI... OK
Running test GRAY:STREAM-FRESH-LINE... OK
Running test GRAY:STREAM-FINISH-OUTPUT... OK
Running test GRAY:STREAM-FORCE-OUTPUT... OK
Running test GRAY:STREAM-CLEAR-OUTPUT... OK
Running test GRAY:STREAM-ADVANCE-TO-COLUMN... FAIL: expected invocation: (gray:stream-advance-to-column #<trivial-gray-streams-test::test-stream2> 10) actual: (gray:stream-line-column #<trivial-gray-streams-test::test-stream2>), (gray:stream-write-string #<trivial-gray-streams-test::test-stream2>
                          "                                                                                                    "
                          0
                          10)
Running test GRAY:STREAM-READ-BYTE... FAIL: Not a binary stream
Running test GRAY:STREAM-WRITE-BYTE... OK
Running test TRIVIAL-GRAY-STREAMS:STREAM-READ-SEQUENCE... OK
Running test TRIVIAL-GRAY-STREAMS:STREAM-WRITE-SEQUENCE... OK
Running test TRIVIAL-GRAY-STREAMS:STREAM-FILE-POSITION... OK
Running test TRIVIAL-GRAY-STREAMS-TEST::SETF-STREAM-FILE-POSITION... OK
(#<TEST-RESULT GRAY:STREAM-READ-CHAR :OK>
 #<TEST-RESULT GRAY:STREAM-UNREAD-CHAR :OK>
 #<TEST-RESULT GRAY:STREAM-READ-CHAR-NO-HANG :OK>
 #<TEST-RESULT GRAY:STREAM-PEEK-CHAR :OK> #<TEST-RESULT GRAY:STREAM-LISTEN :OK>
 #<TEST-RESULT GRAY:STREAM-READ-LINE :OK>
 #<TEST-RESULT GRAY:STREAM-CLEAR-INPUT :OK>
 #<TEST-RESULT GRAY:STREAM-WRITE-CHAR :OK>
 #<TEST-RESULT GRAY:STREAM-LINE-COLUMN :OK>
 #<TEST-RESULT GRAY::STREAM-START-LINE-P :OK>
 #<TEST-RESULT GRAY:STREAM-WRITE-STRING :OK>
 #<TEST-RESULT GRAY:STREAM-TERPRI :OK>
 #<TEST-RESULT GRAY:STREAM-FRESH-LINE :OK>
 #<TEST-RESULT GRAY:STREAM-FINISH-OUTPUT :OK>
 #<TEST-RESULT GRAY:STREAM-FORCE-OUTPUT :OK>
 #<TEST-RESULT GRAY:STREAM-CLEAR-OUTPUT :OK>
 #<TEST-RESULT GRAY:STREAM-ADVANCE-TO-COLUMN :FAIL expected invocation: (gray:stream-advance-to-column #<trivial-gray-streams-test::test-stream2> 10) actual: (gray:stream-line-column #<trivial-gray-streams-test::test-stream2>), (gray:stream-write-string #<trivial-gray-streams-test::test-stream2>
                          "                                                                                                    "
                          0
                          10)>
 #<TEST-RESULT GRAY:STREAM-READ-BYTE :FAIL Not a binary stream>
 #<TEST-RESULT GRAY:STREAM-WRITE-BYTE :OK>
 #<TEST-RESULT TRIVIAL-GRAY-STREAMS:STREAM-WRITE-SEQUENCE :OK>
 #<TEST-RESULT TRIVIAL-GRAY-STREAMS:STREAM-FILE-POSITION :OK>
 #<TEST-RESULT TRIVIAL-GRAY-STREAMS-TEST::SETF-STREAM-FILE-POSITION :OK>)
````

**Comment by kpoeck** [comment]
I fixed GRAY:STREAM-READ-BYTE
Running test GRAY:STREAM-READ-BYTE... OK

**Comment by kpoeck** [comment]
GRAY:STREAM-ADVANCE-TO-COLUMN is not being called, because in the code base calls GRAY:STREAM-ADVANCE-TO-COLUMN. Same problem in ecl, and the clasp code is migrated from ecl

**Comment by kpoeck** [comment]
same problem in ccl

**Comment by kpoeck** [comment]
Nor does the test GRAY:STREAM-ADVANCE-TO-COLUMN works in sbcl

**Comment by kpoeck** [comment]
nor in clisp, so lets ignore that
