### ISSUE TITLE
 (let ((x (gensym))) (write (list x x) :circle t))   doesn't generate the right result

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#350]
Which would be...

(#1=#:G449 #1#)
(#:G449 #:G449)

**Comment by drmeister** [comment]
(let ((*print-circle* t)) (let ((x (gensym))) (print (list x x)) nil))   --> (#:G1028 #:G1028)   FAIL

**Comment by Bike** [comment]
Think this is a dupe of #68 part two
