### ISSUE TITLE
Unhandled Exception of Type 0x4cb3040 When Running Clasp Outside the Build Directory.

### ISSUE THREAD

**Issue by porky11** [clasp-developers/clasp#368]
I installed clasp, now I get this bug, when running clasp:
```
../../src/main/main.cc:391   sizeof(uintptr_clasp_t) -> 8   sizeof(uintptr_t) -> 8
clasp (../../src/main/main.cc:362): The generic catch(...) caught an unhandled exception of type 0x4cb3040 - this is a bug. Please report this to clasp support !
*** BACKTRACE:
stack trace:
  clasp() [0xaa9ee1]
  clasp : gctools::startupGarbageCollectorAndSystem(int (*)(int, char**, bool&, int&, int&), int, char**, unsigned long, bool, int, int)+0xf7
  clasp : main()+0x325
  /usr/lib/libc.so.6 : __libc_start_main()+0xea
  clasp : _start()+0x2a
```
Running clasp in the build directory works without problems

**Comment by Shinmera** [comment]
How exactly did you run clasp if it's not within the build directory

**Comment by porky11** [comment]
I used `./waf install_boehm` and then called it from `/usr/bin/clasp`
btw. shouldn't it be installed into `/usr/local/bin/clasp` by default?

**Comment by drmeister** [comment]
No - clasp doesn't have a default install path.  It installs like a OS X application - all in one directory that you specify in the wscript.config using:
INSTALL_PATH_PREFIX = '/Users/meister/local/clasp/'
