### ISSUE TITLE
Bit functions don't work on non-vectors

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#374]
`(bit-not (make-array '(2 2) :element-type 'bit :initial-element 0))` => "Illegal arguments for bit-array operation"

**Comment by kpoeck** [comment]
I think I fixed that:
````
COMMON-LISP-USER> (bit-not (make-array '(2 2) :element-type 'bit :initial-element 0))
#2A((1 1) (1 1))
````
Please retest

**Comment by kpoeck** [comment]
Fixed, closing
