### ISSUE TITLE
Errors to fix class of

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#375]
- `(setf (symbol-function 4) #'identity)` (expanding into `core:fset`) should signal type-error
- `(makunbound 4)` should signal type-error
- `(undefinedfunctionhere)` should signal undefined-function
- `(apply 1 '(1 2 3))` should signal type-error
- `(hash-table-size 5)` should signal type-error (I believe this and similar are due to `SingleDispatchGenericFunctionClosure_O::slowMethodLookup`)

probably some others

**Comment by kpoeck** [comment]
The following 2 are fixed:
(undefinedfunctionhere) should signal undefined-function
(apply 1 '(1 2 3)) should signal type-error

**Comment by kpoeck** [comment]
These are all fixed, closing
