### ISSUE TITLE
Latest changes to clasp broke callback facility in CFFI support (fli.lsp / cffi-tests)

### ISSUE THREAD

**Issue by dg1sbg** [clasp-developers/clasp#378]
When running cffi-tests then this results in the following error:
#'cmp::get-function-or-error no more available.

Implementing this function again as follows in file src/lisp/kernel/cmp/cmpir.lsp :

    (defun get-function-or-error (module name &optional first-argument)
      (let ((info (gethash name (get-primitives))))
        (unless info (error "Could not find function ~a in *primitives*" name))
        (let ((dispatch-name (resolve-dispatch-name name first-argument info)))
          (let ((func (llvm-sys:get-function module dispatch-name)))
            (unless func
              (error "Could not get function ~S in module ~S (dispatch-name ~S)!" name module dispatch-name))
            (values func info)))))

results in the error
Could not get function "to_object_char" in module #<MODULE ID:5948> (dispatch-name "to_object_char")!

**Comment by Bike** [comment]
I haven't used our CFFI before; how in detail can I reproduce this? Quickload CFFI (or do i need your repo), load some tests/fli.lisp file?

**Comment by dg1sbg** [comment]
(ql:quickload "cffi-tests")
(asdf:test-system "cffi-tests")

**Comment by Bike** [comment]
Reproduced here.

Function was renamed and rewritten in this commit https://github.com/drmeister/clasp/commit/30e2aeb11472e0eb303ad11e741144d7f24699aa#diff-2504f81804a1d86426ee77ee1c593d99

maybe just replacing it will work? Since this additionally declares, unlike yours

**Comment by kpoeck** [comment]
at least interpreted the test run fine;
9 out of 323 total tests failed: DEFCFUN.NOOP, CALLBACKS.LONG, CALLBACKS.BFF.2, CALLBACKS.NON-EXISTANT, 
   CALLBACKS.UNINTERNED, MAKE-POINTER.HIGH, FSBV.WFO, FSBV.MAKEPAIR.1, 
   FSBV.MAKEPAIR.2.
6 unexpected failures: DEFCFUN.NOOP, CALLBACKS.LONG, CALLBACKS.BFF.2, CALLBACKS.NON-EXISTANT, 
   CALLBACKS.UNINTERNED, MAKE-POINTER.HIGH.
