### ISSUE TITLE
The standard readtable sucks

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#391]
That is, the one you get from `(copy-readtable nil)`, not the startup readtable, which is okay.

`#a` is defined as an implement-me, giving rise to #382. `#=` is undefined, which seems to be the culprit behind #91.

The standard readtable is defined with create_standard_readtable in core/readtable.cc. It is interpreter level and so doesn't know about all our nice working reader macros.

It's possible that avoiding bootstrapping and/or defining the reader in lisp will incidentally fix this issue.

**Comment by drmeister** [comment]
I see - I'd like to punt this until we have switched to the CST compiler.  The CST compiler uses the eclector reader and we can then switch to the eclector reader for everything.

**Comment by kpoeck** [comment]
This is fixed now, the lisp definde readers are even in (copy-readtable nil)
