### ISSUE TITLE
#define free and #define malloc cause problems when including other SW packages' header files

### ISSUE THREAD

**Issue by dg1sbg** [clasp-developers/clasp#403]
In file 
`include/clasp/core/queue.h
`
we find the following lines of code:

  ```
#ifdef USE_BOEHM
    #define malloc(size) reinterpret_cast<void*>(gctools::malloc_uncollectable_and_zero(size))
    #define free(ptr) GC_FREE(ptr)
  #endif
  #ifdef USE_MPS
    #define malloc(size) NULL /* printf("%s:%d IMPLEMENT malloc(%lu)for mps\n", __FILE__, __LINE__, size);abort(); */
    #define free(ptr) /* nothing */
  #endif
#
```

This is causing problems in other SW's sources: std::free()  is translated into std::GC_FREE() ... Not good. ;-)

**Comment by drmeister** [comment]
Try commenting this out - it may be an artifact from when I incorporated the C++ concurrent lockless queues.

**Comment by dg1sbg** [comment]
As drmeister advised I removed the culprit. I did so by entirely removing files queue.h/queue.cc as they are only dead code / empty.

**Comment by dg1sbg** [comment]
Will be fixed by pull request.

**Comment by Bike** [comment]
Don't see a PR. I just deleted all the queue code (69e6bd3203c35f1ce51e34efac28a4fb4f8ef0ba) so I think this should no longer be a problem.

**Comment by Bike** [comment]
The file is gone and the string `#define malloc` is no longer in the code, so I think we're good here.
