### ISSUE TITLE
ansi-tests: (GENTEMP "Y" #\Z) -> Package error on package "90"

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#417]
complete to reproduce
````
COMMON-LISP-USER> (defpackage "Z")
#<Z>
COMMON-LISP-USER> (GENTEMP "Y" "Z")
Z::Y107
COMMON-LISP-USER>  (GENTEMP "Y" #\Z)
Condition of type: PACKAGE-ERROR
Package error on package "90"
Available restarts:
(use :r1 to invoke restart 1)
1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
Broken at frame[0] NIL. In: #<PROCESS TOP-LEVEL @0x108eb1e09>.
````
since (char-int #\Z) == 90 probably something fishy in happening here

**Comment by Bike** [comment]
There are similar errors with `intern` and so on. Likely the problem is `coerce::packageDesignator` in designators.cc, but I don't see any obvious problem on a cursory look. Perhaps clasp_as_claspCharacter is understood as a number by the `<<` operator.

**Comment by Bike** [comment]
Dunno what the problem is. Maybe the `&` that was there made it a number. Anyway I just copied how it works for string designators.

@kpoeck try now, please

**Comment by kpoeck** [comment]
works like a charm, a lot less errors in the ansi-tests, perhaps we go below 1000 errors (from 1700 or so)!

**Comment by drmeister** [comment]
kpoeck - this is awesome work - thank you very much.
