### ISSUE TITLE
ansi-tests: FILL of bit arrays fills entire blocks regardless of :start/:end

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#436]
correct:
````
CL-TEST> (progn (core::fill-array-with-elt (setq der (make-array 7 :initial-element 2)) 5 0 3) der)
#(5 5 5 2 2 2 2)
````
Wrong:
````
CL-TEST> (progn (core::fill-array-with-elt (setq der (make-array 7 :initial-element 0 :element-type 'bit)) 0 0 3) der)
#*1111111
````

**Comment by Bike** [comment]
Internal functions can do whatever we want, so to be clear

    (let ((seq (make-array 35 :initial-element 0 :element-type 'bit)))
      (fill seq 1 :start 7 :end 19)
      seq)

demonstrates the problem. It returns `#*11111111111111111111111111111111000`.

`SimpleBitVector_O::unsafe_fillArrayWithElt` is probably the culprit. To summarize, bit arrays are stored differently from other arrays, in that in an underlying sense the "element type" is 32 bit words. The C++ method tries to fill whole words at once when it can, but it is not doing so correctly.

**Comment by kpoeck** [comment]
````
void SimpleBitVector_O::unsafe_fillArrayWithElt(T_sp initialElement, size_t start, size_t end) {
  if (CLASP_FIXNUMP (initialElement))
  {
    Fixnum zero_or_one = clasp_fixnum(gc::As<core::Fixnum_sp>(initialElement));
    if ((zero_or_one == 0) || (zero_or_one == 1)) {
      for (size_t i(start),iEnd(end); i<iEnd; ++i) {
        this->setBit(i, zero_or_one);
      }
    }
    else TYPE_ERROR(initialElement, cl::_sym_bit);
  }
  else TYPE_ERROR(initialElement, cl::_sym_bit);
}
````
Seem to work fine, will do more testing before pr

**Comment by kpoeck** [comment]
should read "i<=iEnd"

**Comment by kpoeck** [comment]
Äh, no, < is fine

**Comment by kpoeck** [comment]
so with pr #512 
````
COMMON-LISP-USER> (fill (make-array 7 :initial-element 0 :element-type 'bit) 1 :start 3 :end 5)

#*0001100
````
