### ISSUE TITLE
BOOLE with bad fixnum crashes

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#438]
`boole` with a non-integer properly signals a type error.

With a fixnum that isn't a valid boole op, though, it crashes. For example `(boole 373 1 1)`.

This is due to using an array access like `fixnum_operations[op]` to find a function to call, in bits.cc.

**Comment by kpoeck** [comment]
please check, I think I fixed this

**Comment by Bike** [comment]
Yep.
