### ISSUE TITLE
Ansi-tests: some string routines should accept &key start end 

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#441]
See:
http://www.lispworks.com/documentation/HyperSpec/Body/f_stg_up.htm

Wrong (written in c++)

- string-upcase
- STRING-DOWNCASE
- NSTRING-UPCASE
- NSTRING-DOWNCASE

Good (written in lisp)

- STRING-CAPITALIZE
- NSTRING-CAPITALIZE

**Comment by kpoeck** [comment]
this is all array.cc if I see that correctly.
Might be easiest to write all that in Lisp, but still not sure where to fix things?

Can we write things in lisp that are not needed during bootstrap?

**Comment by Bike** [comment]
Not sure I understand the question.

**Comment by kpoeck** [comment]
I think it is should be possible to write string-upcase, STRING-DOWNCASE, NSTRING-UPCASE, NSTRING-DOWNCASE in lisp adding the &key start end.

Is this ok, or would this give problems while building?

**Comment by Bike** [comment]
Ah, you mean having a lisp definition in addition to the C++ definition. No, I think that should work.

**Comment by Bike** [comment]
This is probably a duplicate of #218. Just noting that so I remember to close both if you fix it.

**Comment by kpoeck** [comment]
Fixed with pr #448, please check also #218

**Comment by kpoeck** [comment]
retest after rebuild fine
