### ISSUE TITLE
DEFGENERIC doesn't create methods on same pass as creating generics

### ISSUE THREAD

**Issue by dkochmanski** [clasp-developers/clasp#487]
For the original issue see: https://gitlab.com/embeddable-common-lisp/ecl/issues/46

I've fixed it today in ECL, but defmethod macro in clasp has diverged too much to simply backport the change, hence I'm reporting a bug with explanation and solution I've used.

## Problem

`defmethod` macro calls `ensure-generic-function` at macroexpansion time. That may lead this form to behave weirdly when you load it:

```
(unless (fboundp 'foo)
  (defgeneric foo ()
    (:method () :foo)))
```

namely defgeneric expands into something like

```
(progn
  (ensure-gf ..)
  (defmethod ..))
```

what is a correct expansion, but defmethod calls ensure-gf at macroexpansion time, so fboundp returns T and body is not executed – yet generic function is created! So we have generic function foo without a method.

## Solution

Instead of calling ensure-generic-function in defmethod (we need gf prototype for `make-method-lambda`) we call  a new function which behaves better wrt creating gfs (that is – it doesn't create them).

```
(defun prototypes-for-make-method-lambda (name)
  (if (not *clos-booted*)
      (values nil nil)
      (let ((gf? (and (fboundp name)
                      (fdefinition name))))
        (if (or (null gf?)
                (not (si:instancep gf?)))
            (values (class-prototype (find-class 'standard-generic-function))
                    (class-prototype (find-class 'standard-method)))
            (values gf?
                    (class-prototype (or (generic-function-method-class gf?)
                                         (find-class 'standard-method))))))))
```

and we replace `let*` with `m-v-b`
```
(let* ((generic-function (ensure-generic-function name))
	 (method-class (generic-function-method-class generic-function))
	 method #|I don't know what role this variable plays, clasp-specific|#)
  ...)
```

```
(multiple-value-bind (generic-function method)
            (prototypes-for-make-method-lambda name)
  (mvb (fn-form opts) (make-method-lambda generic-function method lambda-form env)
    ...)
```

or something like this.

**Comment by Bike** [comment]
adopted with pretty much no changes. thanks.
