### ISSUE TITLE
A mistake in Clasp 0.5 Build Instructions

### ISSUE THREAD

**Issue by gzll** [clasp-developers/clasp#489]
There is a mistake in Clasp 0.5 Build Instructions of the Wiki.
The 6th of the instructions' steps should be: ./waf update_dependencies configure build_cboehm

**Comment by attila-lendvai** [comment]
that's for v0.5.

if you want to build the `dev` branch, then it's enough to just `./waf distclean configure build_cboehm`.

**Comment by attila-lendvai** [comment]
i've merged and updated the build instructions page:

https://github.com/clasp-developers/clasp/wiki/Build-Instructions
