### ISSUE TITLE
ansi-tests: typep in some forms with arrays no longer working

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#497]
````
CL-USER> (TYPEP #2A(()) '(ARRAY T))
T
CL-USER> (let () (TYPEP #2A(()) '(ARRAY T)))
NIL
````

**Comment by kpoeck** [comment]
Ok, is defined in opt-type.lsp, but not obvious how this could fail

**Comment by kpoeck** [comment]
(funcall (compiler-macro-function 'typep) '(TYPEP #2A(()) '(ARRAY T)) nil)
->
(IF (CLEAVIR-PRIMOP:TYPEQ #2A(()) (ARRAY T)) T NIL)
-> nil

**Comment by Bike** [comment]
The lowering is actually done in a more opaque hir-to-mir step. (Which is bad, but Cleavir's handling of types is still kind of in flux.)

**Comment by Bike** [comment]
Got dev fresh and still can't reproduce.

If you saw this behavior prior to fd428c4, it is possibly due not to `typep` but to `make-array`, which I had broken such that it would not make multidimensional arrays, though I'm not totally sure that would work with the read macro situation.

**Comment by kpoeck** [comment]
For whatever reason now happens again in vanilla clasp from dev

**Comment by kpoeck** [comment]
Great, will test this evening

**Comment by kpoeck** [comment]
did fix as bike said
