### ISSUE TITLE
Ansi-tests: clos accessors accept any number of arguments

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#516]
The following should fail
````
CL-USER> (defclass test ()((foo :initform :bar :accessor test-foo)))
#<The STANDARD-CLASS COMMON-LISP-USER::TEST>
CL-USER> (test-foo (make-instance 'test) 23 24 25)
:BAR
````

**Comment by Bike** [comment]
This is because discriminating functions do not actually check argument counts - methods do - and accessors bypass methods. I'm not sure how to fix this but that is the problem.

**Comment by kpoeck** [comment]
OK, will also try to check this

**Comment by Bike** [comment]
This should be fixed as of fdd862a, at least for memoized calls. For the first call it still accepts too many arguments.

**Comment by Bike** [comment]
And 75c7e42 for too many arguments. Still wanna fix that LAMBDA crapola tho.

**Comment by kpoeck** [comment]
Fixed, great!
