### ISSUE TITLE
ansi-test: reverse of displaced vector seems wrong

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#521]
````
(reverse
	  (make-array 3 :displaced-to
		      (make-array 5 :initial-contents (list 0 1 2 3 4))
		      :displaced-index-offset 1))
#(2 1 NIL)
````
but
````
CL-USER> (reverse
	  (copy-seq (make-array 3 :displaced-to
		      (make-array 5 :initial-contents (list 0 1 2 3 4))
		      :displaced-index-offset 1)))
#(3 2 1)
````
which seems correct

**Comment by kpoeck** [comment]
goes to 
* CL_DEFUN T_sp cl__reverse(T_sp seq)
*  arr->reverse();
* virtual Array_sp reverse() const final { return templated_reverse_VectorNs(*this); };
*  template <class T>
    Array_sp templated_reverse_VectorNs(T& me) {
    AbstractSimpleVector_sp bsv;
    size_t start, end;
    me.asAbstractSimpleVectorRange(bsv,start,end);
    auto sv = gc::As_unsafe<gctools::smart_ptr<typename T::simple_type>>(bsv);
    return templated_ranged_reverse<typename T::simple_type>(*sv,start,end);
  }
* here start, end are 1 4 and things go wrong

**Comment by Bike** [comment]
start=1, end=4 makes sense to me, provided bsv is the actual underlying simple vector. Maybe it's not?

**Comment by Bike** [comment]
I'm seeing `#(3 2 1)` after this commit.

`nreverse` doesn't seem to work, but I think it's a separate problem

**Comment by kpoeck** [comment]
great!
