### ISSUE TITLE
ansi-tests: more equalp errors

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#523]
````
CL-USER> (equalp "ab" #(#\a #\b))
NIL
````
should return T.

I wonder whether it is better to rewrite in lisp

**Comment by kpoeck** [comment]
also
````
(let ((vector (make-array 3 :fill-pointer 2 :initial-contents (list 1 2 3))))
     (equalp vector (copy-seq vector)))
````
should return true

**Comment by drmeister** [comment]
I made a fix in 61b77d857 to fix a segfault in Array_O::equalp - it didn't fix either of these.

**Comment by Bike** [comment]
The particular issue with "ab" seems to be due to the equalp methods rejecting non-strings right off. I think that won't be hard to fix - testing it now. Not sure about the other yet.

**Comment by Bike** [comment]
Think I got it. @kpoeck, could you run the tests again?

**Comment by kpoeck** [comment]
works fine now, get unexpected successes in the regression-tests now!
