### ISSUE TITLE
Ansi-tests: integer-length for negative bignums seem to be off by 1

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#536]
clasp
````
CL-USER> (integer-length (- (ash 1 62)))
63
````
sbcl
````
CL-USER> (integer-length (- (ash 1 62)))
62
````

**Comment by kpoeck** [comment]
probably by this code in bignum.cc
````
gc::Fixnum Bignum_O::bit_length_() const {
  Bignum x = this->_value;
  if (this->sign() < 0) {
    x = -x;
  }
  return mpz_sizeinbase(x.get_mpz_t(), 2);
}
````

**Comment by kpoeck** [comment]
positive bignums seem to work fine.

See documentation in [https://gmplib.org/manual/Miscellaneous-Integer-Functions.html](https://gmplib.org/manual/Miscellaneous-Integer-Functions.html)

They say sign is not important, so perhaps the x =-x is superflous

**Comment by Bike** [comment]
It is superfluous, but the results are still wrong without it.

CL treats negative numbers differently from GMP. `(integer-length -8)` is one less than `(integer-length 8)`. But it's more complicated and overall that documentation says "The result will be either exact or 1 too big." which like, okay. What can we possibly do with that shit.

**Comment by kpoeck** [comment]
Well they say:
 If base is a power of 2, the result is always exact. I assume this means the call with base 2 is exact. I will try returning 1- the result from gmp if the number is negative

**Comment by Bike** [comment]
You're right, I misread it as if the _number_ is a power of two. That's more sensible.
