### ISSUE TITLE
Speed up cl:write and cl:pprint-dispatch

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#537]
Clasp inherited cl:pprint-dispatch from ECL and it is pretty slow.

Could we use the generic function discriminator compiler to speed it up?

We could create an alist of (class . pprint-dispatcher)  and generalize the discriminator compiler to generate discriminator functions that would check the stamp of the object and dispatch to return the appropriate pprint-dispatcher or fall through to a default function that calculates the pprint-dispatcher.

**Comment by Bike** [comment]
pprint dispatch doesn't work with classes, it works with types.

Pretty printing is also seriously complicated and I'd expect it to be slow for manifold reasons. Is it a bottleneck somewhere?

**Comment by drmeister** [comment]
Trying this in email.

I thought it was - and then afterwards I realized I was doing the timing
wrong.
So I'll leave this alone.

On Wed, Jun 27, 2018 at 6:04 AM, Неточка Незванова <notifications@github.com
