### ISSUE TITLE
Missing steps in MacOS installation instructions

### ISSUE THREAD

**Issue by mdittmer** [clasp-developers/clasp#541]
To install clasp on OS X today I followed [these instructions](https://github.com/clasp-developers/clasp/wiki/Build-Instructions#macos) using the `master` branch, but I needed to perform the following undocumented steps:

```bash
# Put llvm@5 in PATH:
export PATH="/usr/local/opt/llvm@5/bin:$PATH"
# Install missing dependency: sbcl
brew install sbcl
```

Once these were in place, `./waf configure` worked properly, but `./waf build_cboehm` failed on the `master` branch. Next, I tried the `dev` branch, on which `./waf configure` failed. Finally, I tried the `testing` branch, and no luck with `./waf build_cboehm` there either.

I can post detailed logs if this is the appropriate venue for debugging but I thought, at the least, I should file an issue pointing out the prerequisites missing from the instructions.

**Comment by kpoeck** [comment]
I can compile dev fine. What might be missing that you need to get brew install llvm@6 too (and LLVM_CONFIG_BINARY = '/usr/local/opt/llvm@6/bin/llvm-config' in wscript.config)

**Comment by kpoeck** [comment]
I didn't need to do the export PATH="/usr/local/opt/llvm@5/bin:$PATH" though

**Comment by mdittmer** [comment]
Does that mean, perhaps, that the instructions should replace `llvm@5` with `llvm@6`, too?

**Comment by mdittmer** [comment]
Dropping llvm@5 from `PATH` and putting `LLVM_CONFIG_BINARY = '/usr/local/opt/llvm@6/bin/llvm-config' into `wscript.config` worked. So, perhaps `sbcl` and a mention of how to setup `wscript.config` would improve the install instructions. Thanks for the quick response!!

**Comment by kpoeck** [comment]
I am glad that you deciphered my comment correctly, to summarize:

- the build instructions miss sbcl as a dependencies
- the build instruction should mention that now llvm@6 is to be used instead of llvm@5
- they should mention that  LLVM_CONFIG_BINARY = '/usr/local/opt/llvm@6/bin/llvm-config'  needs to go to wscript.config

**Comment by mdittmer** [comment]
Exactly right!

**Comment by kpoeck** [comment]
Instructions improved
