### ISSUE TITLE
ansi-tests: sxhash should return a positive fixnum

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#558]
```lisp
(typep (SXHASH (MAKE-SYMBOL "FOO")) 'fixnum)
NIL
(type-of (SXHASH (MAKE-SYMBOL "FOO")))
(INTEGER 8995143153023308406 8995143153023308406)
````
but in clhs http://www.lispworks.com/documentation/HyperSpec/Body/f_sxhash.htm
Function SXHASH
Syntax:
sxhash object => hash-code
Arguments and Values:
object---an object.
hash-code---a non-negative fixnum.

**Comment by kpoeck** [comment]
cl__sxhash returns Integer_O::create(hg.hash());
hg.hash returns a  gc::Fixnum
a gc::Fixnum might not always fit in a lisp fixnum?

**Comment by Bike** [comment]
a `gc::Fixnum` is, i think, an `int64_t`, so yeah you can fit non fixnums in there. Problematic. I guess we could like, shift out the low bits, or something...?

**Comment by kpoeck** [comment]
This gives a runtime error in mcclim in incremental-redisplay, since there the result of sxhash is declared fixnum and obviously this is checked at runtime.

Will try to shift 2 bits to the right

**Comment by kpoeck** [comment]
Should have it now correct will send pr
