### ISSUE TITLE
(+ 1/2 1/2) should be 1 not 1/1

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#567]
If I understand http://www.lispworks.com/documentation/HyperSpec/Body/t_ratio.htm correctly

"... and of which the denominator is positive and greater than one."

**Comment by kpoeck** [comment]
I have solved the case of 1/1, but need to solve the general case where the denominator is 1

**Comment by kpoeck** [comment]
(+ 1/2 1/2 1/2 1/2) now works, but e.g. 4/1 does not

**Comment by Bike** [comment]
Fixed by #594
