### ISSUE TITLE
New Lisp dialect with no gc rely (use reference count and develop by C++) call for notice and help.

### ISSUE THREAD

**Issue by wangyang2010344** [clasp-developers/clasp#574]
[main page](https://github.com/wangyang2010344/S-Lisp)
[demo](https://github.com/wangyang2010344/S-Lisp/blob/master/C%2B%2B/S/test/t.lisp)
it is designed with no circular reference it can precisely reclaim memory，and how it achieve？please check the code.only 8 source file so it only spend a little time. and I have difficult in reclaim memory when exception.and debug etc is also in need.so I call for help,and I think this type of lisp grammer can also be helpful for you.thanks!

sorry for my broken English.

**Comment by Shinmera** [comment]
This has no relation to Clasp.
