### ISSUE TITLE
Ansi-tests: (eql (gcd 0 1) 1) -> nil

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#578]
but
(= (gcd 0 1) 1)
-> t

**Comment by kpoeck** [comment]
Looking at the code gcd is returning a bignum:
```lisp
(typep (gcd 0 1) 'bignum)
-> t
````

**Comment by kpoeck** [comment]
So probably in clasp_gcd
before returning _clasp_big_gcd(gc::As<Bignum_sp>(x), gc::As<Bignum_sp>(y));
we need to check whether the result fits in a Fixnum and convert to a Fixnum_sp if possible

**Comment by kpoeck** [comment]
The following seems to work:
```c++
Bignum_sp temp = _clasp_big_gcd(gc::As<Bignum_sp>(x), gc::As<Bignum_sp>(y));
  if (temp->fits_sint_p())
    return clasp_make_fixnum(temp->as_int());
  else return temp;    
````

but might be wastefull to call _clasp_big_gcd for fixnums

**Comment by Bike** [comment]
It is, but "slow" is preferable to "slow and broken" anyway. Uh, and your fix seems to just do Euclid's algorithm for fixnums anyway, great.

**Comment by kpoeck** [comment]
Now:
```lisp
CL-USER> (eql (gcd 0 1) 1)
T
````
