### ISSUE TITLE
Additional IEEE Float Features

### ISSUE THREAD

**Issue by Shinmera** [clasp-developers/clasp#583]
This is for a compatibility library called [float-features](https://github.com/Shinmera/float-features) that offers additional parts about floats not covered by the CL standard. In order to support Clasp, Clasp needs to offer me the following constants:

* [x] `short-float-positive-infinity`
* [x] `short-float-negative-infinity`
* [x] `single-float-positive-infinity`
* [x] `single-float-negative-infinity`
* [x] `double-float-positive-infinity`
* [x] `double-float-negative-infinity`
* [x] `long-float-positive-infinity`
* [x] `long-float-negative-infinity`

And the following functions:

* [x] `float-infinity-p`
* [x] `float-nan-p`
* [x] `short-float-bits`
* [x] `single-float-bits`
* [x] `double-float-bits`
* [x] `long-float-bits`
* [x] `bits-short-float`
* [x] `bits-single-float`
* [x] `bits-double-float`
* [x] `bits-long-float`

If Clasp signals conditions on floating point traps/signals such as overflow, underflow, inexact, invalid, or divide-by-zero, then it should also offer a way to change which signals are masked or not, either by a global change function or a lexical macro:

* [x] `with-float-traps-masked` / `set-floating-point-modes`

For more information, please see the current [implementation](https://github.com/Shinmera/float-features/blob/master/float-features.lisp).

Please edit my post with the appropriate Clasp names for the required features if or when they exist.

**Comment by kpoeck** [comment]
ext::short-float-positive-infinity
ext::short-float-negative-infinity
ext::single-float-positive-infinity
ext::single-float-negative-infinity
ext::double-float-positive-infinity
ext::double-float-negative-infinity
ext::long-float-positive-infinity
ext::long-float-negative-infinity

in c++ there is
clasp_float_nan_p
clasp_float_infinity_p
but neither of them seems to be exposed to lisp

**Comment by Shinmera** [comment]
Thanks! It would be good if those constants and functions were exported from ext, so that I don't need to rely on internals.

**Comment by kpoeck** [comment]
Ok, testing now (exporting the symbols for *infinity and exposing float-nan-p and float-inifinity-p to lisp)

**Comment by kpoeck** [comment]
Seems to fit your implementation, so let me create a pr with my mods

**Comment by Shinmera** [comment]
Look above, I already committed a patch that includes the currently exposed functionality.

**Comment by kpoeck** [comment]
I did look, thats why i wrote "Seems to fit your implementation"

**Comment by Shinmera** [comment]
Ah- I misunderstood, I thought you meant that you were going to submit a PR to float-features.

**Comment by kpoeck** [comment]
This is now all merged in dev of clasp with #585. Don't know if you can build again to test. If there is some kind of test-suite, I could execute that if you can't

**Comment by Shinmera** [comment]
No. I can't build, and the way the library is written it's not really pollible to write sensible tests beyond loading the library and looking at the values of the constants manually.

**Comment by Shinmera** [comment]
I'm going to leave this open to track the addition of `with-float-traps-masked`

**Comment by Shinmera** [comment]
Now that FPE exceptions actually cause conditions to be signalled, adding a way to change which exceptions cause traps through a `with-float-traps-masked` construct would be great.

**Comment by Shinmera** [comment]
The float-features protocol has been extended.

Namely I need functions to encode and decode floats from and to their bit formats.
Please see the [existing implementation](https://github.com/Shinmera/float-features/blob/master/float-features.lisp#L229-L330) if it's unclear what I mean.

**Comment by kpoeck** [comment]
did #845 to implement the missing float-features protocol

**Comment by kpoeck** [comment]
single-float-bits = CORE:SINGLE-FLOAT-BITS
double-float-bits = core:double-float-bits
bits-single-float = core:single-float-from-unsigned-byte-32 
bits-double-float= core:double-float-from-bits

**Comment by kpoeck** [comment]
I defined the missing `with-float-traps-masked` so this can probably be closed

**Comment by Bike** [comment]
We should probably move those functions to ext. also shorten the -from-unsigned-byte-32 so it matches

**Comment by Bike** [comment]
Did that as 7365c8453.

**Comment by Shinmera** [comment]
Seems like this is done now, nice!
