### ISSUE TITLE
:POISON-VALUE-FROM-CODEGEN-RTV is not of type INTEGER.

### ISSUE THREAD

**Issue by pfdietz** [clasp-developers/clasp#597]
In current dev build:

(funcall (compile nil '(lambda () (load-time-value (dpb 0 (byte 0 0) 0)))))

==>

:POISON-VALUE-FROM-CODEGEN-RTV is not of type INTEGER.
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RESTART-TOPLEVEL] Go back to Top-Level REPL.

Backtrace:
  0: (UNIVERSAL-ERROR-HANDLER NIL TYPE-ERROR (:DATUM :POISON-VALUE-FROM-CODEGEN-RTV :EXPECTED-TYPE INTEGER))
  1: (ERROR TYPE-ERROR :DATUM :POISON-VALUE-FROM-CODEGEN-RTV :EXPECTED-TYPE INTEGER)
  2: UNKNOWN-LISP-FUNCTION
  3: UNKNOWN-LISP-FUNCTION
  4: (MAKE-APINT-WIDTH :POISON-VALUE-FROM-CODEGEN-RTV 64 T)
  5: (JIT-CONSTANT-I64 :POISON-VALUE-FROM-CODEGEN-RTV)
  6: (%I64 :POISON-VALUE-FROM-CODEGEN-RTV)
  7: ((METHOD TRANSLATE-SIMPLE-INSTRUCTION (PRECALC-VALUE-INSTRUCTION T T T T T)) #<VA-LIST: (#<CLASP-CLEAVIR-HIR:PRECALC-VALUE-INSTRUCTION> #<ALLOCA-INST@0x5439fd68   %return-value = alloca { {}*, i64 }> ..
  8: (LAMBDA)
  9: (LAMBDA)
[...]

**Comment by Bike** [comment]
we have this as #404 i think
