### ISSUE TITLE
functions defined as CL_DEFUN void cl__* that should return nil

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#608]
Same pattern as for sleep:
- terpri &optional output-stream => nil
- clear-input &optional input-stream => nil
- clear-output &optional output-stream => nil
- finish-output &optional output-stream => nil
- force-output &optional output-stream => nil
- unread-char character &optional input-stream => nil
- cerror continue-format-control datum &rest arguments => nil

Fix: define as 
- CL_DEFUN T_sp cl__*
- end with return _Nil<T_O>();

**Comment by Bike** [comment]
You gonna do a PR for this or should I fix it up?

**Comment by kpoeck** [comment]
I can do, no problem
