### ISSUE TITLE
ansi-test:  write-to-string optimisation not working

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#609]
(write-to-string (vector nil nil))
-> a lot of garbage

(length (write-to-string (vector nil nil)))
-> 1538134

**Comment by kpoeck** [comment]
might only be happening when ansi-tests are loaded, will check which print-variables are set

**Comment by Bike** [comment]
I'm seeing it print as "#(NIL [fuckton of space] NIL)", is that what you mean?

It gets longer every time I do it. Wtf

**Comment by Bike** [comment]
`*print-pretty*` T seems to be the basic requirement

**Comment by kpoeck** [comment]
Yes, i meant the fuckton of space before nil. Does not happen with the previous definition of write-to-string

**Comment by drmeister** [comment]
I think I found the problem.   There is a StreamOutputColumn(strm) that keeps track of the output column for pretty printing.  I wasn't resetting it after calling core__get_thread_local_write_to_string_output_stream_string.
I do now.

**Comment by kpoeck** [comment]
Well lets build and run the ansi-tests to confirm

**Comment by Bike** [comment]
Seems fixed to me. Is there a particular way to test in relation to ansi-tests?

**Comment by kpoeck** [comment]
The lots of garbage is fixed, so closing
