### ISSUE TITLE
(exp 2000e0) now fails while printing

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#618]
```lisp
COMMON-LISP-USER>>  (exp 2000e0)
Debugger received error of type: TYPE-ERROR
"#.ext:double-float-positive-infinity" is not of type CORE:STR-NS.
````

Error is for sure in core_float_to_string_free in
```c++
else if (clasp_float_infinity_p(number)) {
    T_sp s = eval::funcall(ext::_sym_float_infinity_string, number);
    return push_base_string(buffer_or_nil, gc::As<StrNs_sp>(s));
````

Obviously s is not a StrNs_sp, but I don't know which type it really is. Since push_base_string  expects a StrNs_sp, I don't see an easy fix, meaning I don't know how to fix it.

**Comment by Bike** [comment]
Seems to be a simple base string (source: `class-of`) as the name implies. I think drmeister's change in 4bf84fdf may not have been perfect. I changed it to simple base string and it works for me now.

**Comment by kpoeck** [comment]
and fixed
