### ISSUE TITLE
Building on Ubuntu requires libelf-dev

### ISSUE THREAD

**Issue by mardukbp** [clasp-developers/clasp#652]
In the current build instructions for Ubuntu, along with `libelf1` it is necessary to install `libelf-dev`. Otherwise `waf` complains that it cannot find the `elf` library. This is the case for Ubuntu 18.04. It might also be true for older versions.

**Comment by kpoeck** [comment]
I adapted https://github.com/clasp-developers/clasp/wiki/Build-Instructions to include libelf-dev

**Comment by drmeister** [comment]
Thank you!

**Comment by kpoeck** [comment]
Build instructions fixed so closing
