### ISSUE TITLE
Has anyone tried building on ARM?

### ISSUE THREAD

**Issue by cellularmitosis** [clasp-developers/clasp#679]
Hello,

I've just downloaded clasp and am attempting to build it on a raspberry pi, but I wanted to ask if anyone has tried building this on ARM before, and if you had any advice.

Thanks!

**Comment by cellularmitosis** [comment]
Ran into this pretty quickly :)

```
clasp/src/core/corePackage.cc:1251:2: error: Currently only x86_64 and i386 is supported
```

**Comment by kpoeck** [comment]
I believe this is answered

**Comment by pepasflo** [comment]
👍
