### ISSUE TITLE
*print-circle* shouldn't affect symbols

### ISSUE THREAD

**Issue by stassats** [clasp-developers/clasp#68]
`(let ((*print-circle* t)) (princ '(a a)))` is printed as (#1=A #1#)
while clhs says:
"Note that implementations should not use #n# notation when the Lisp reader would automatically assure sharing without it
(e.g., as happens with interned symbols)."

Which also means that `(let ((*print-circle* t)) (princ '(#1=#:a #1#)))`
should be printed as (#1=A #1#)

**Comment by Shinmera** [comment]
Cannot confirm the first, but can confirm the latter on b05884f.
```
> (let ((*print-circle* t)) (princ '(a a)))
(A A)
(A A)
> (let ((*print-circle* t)) (princ '(#1=#:a #1#)))
(A A)
(#:A #:A)
```
