### ISSUE TITLE
Method Dispatch on VECTOR Specialisation Fails With Adjustable Vectors

### ISSUE THREAD

**Issue by Shinmera** [clasp-developers/clasp#698]
```common-lisp
(defmethod foo ((vector vector)) vector)
(foo (make-array 0 :adjustable T))
; => Error, no applicable method
```

**Comment by Bike** [comment]
`(typep (make-array 0 :adjustable t) (find-class 'vector)) => NIL`
`(subtypep 'core:mdarray-t 'vector) => T T`
`(subtypep (find-class 'core:mdarray-t) (find-class 'vector)) => NIL T`
the fact that the class-of an adjustable vector is mdarray is probably going to be an issue. also the class hierarchy is busted.

**Comment by drmeister** [comment]
Does anyone have any suggestions on how to fix this?
What direction do we need to go?

**Comment by drmeister** [comment]
Currently MDArray_O and things like it are used to represent adjustable one-dimensional arrays.
But when they have a rank=1 they are not recognized as vectors.
We could either change the predlib code to recognize 1D MDArray_O as vectors or
break out another class for every array type that handles adjustable, fill-pointerable vectors.

**Comment by kpoeck** [comment]
Works now, did define regression test for clos.lisp (pr pending)
(defmethod foo-bar ((vector vector)) vector)

(test issue-698
      (vectorp (foo-bar (make-array 23 :adjustable T))))
