### ISSUE TITLE
AST-TOOLING package has bad nickname

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#699]
`(package-nicknames (find-package "AST-TOOLING")) => (NIL)`

It should of course be `()`. This is apparent all the way back to iclasp, so I assume it's part of the C++ package definition. However things look okay in my generated `symbols_scraped_inc.h` so I don't know what's up.

Package nicknames must be strings. This problem results in SLIME's `slime-repl-set-package` aka `,i` command not working with Clasp.

**Comment by kpoeck** [comment]
I wonder whether this comes from astExpose.h with
PACKAGE_USE("COMMON-LISP");
PACKAGE_NICKNAME("CAST");
NAMESPACE_PACKAGE_ASSOCIATION(clang_ast,ClangAstPkg,"CLANG-AST");
and the empty nickname is actually "CAST"

**Comment by kpoeck** [comment]
Unfortunately it does not help

**Comment by kpoeck** [comment]
What does help is the following in claspTooling.cc (changing "CLANG" to "AST-TOOLING"
```c++
void initialize_clangTooling() {

  initialize_matchers();
  // overloaded functions that had trouble resolving
  clang::ASTContext &(clang::ASTUnit::*clang_ASTUnit_getASTContext)() = &clang::ASTUnit::getASTContext;
  package(AstToolingPkg, {"AST-TOOLING"}, {}) // {"CLANG"}, {}) // , {"CL", "CORE", "AST-TOOLING"})
... 
````

Will test some more and send pr

**Comment by kpoeck** [comment]
And this was wrong again, this works:
```c++
void initialize_clangTooling() {

  initialize_matchers();
  // overloaded functions that had trouble resolving
  clang::ASTContext &(clang::ASTUnit::*clang_ASTUnit_getASTContext)() = &clang::ASTUnit::getASTContext;
  package(AstToolingPkg, {}, {}) // {"CLANG"}, {}) // , {"CL", "CORE", "AST-TOOLING"})
````
The following test runs fine (and ,i in slime)
```lisp
(every #'(lambda(package)
                 (cond ((and (every #'stringp (package-nicknames package))
                             (every #'packagep (package-use-list package))
                             (every #'packagep (package-used-by-list package))
                             (stringp (package-name package))))
                       (t (format t "Error in package-tests for ~s" package)
                          nil)))
             (list-all-packages))
````

**Comment by Bike** [comment]
kpoeck's fix works.
