### ISSUE TITLE
defclass accepts invalid options

### ISSUE THREAD

**Issue by dkochmanski** [clasp-developers/clasp#703]
Steps to reproduce:

(defclass xxx nil nil nil)

should error (nil is not valid initarg). Originally reported here: https://gitlab.com/embeddable-common-lisp/ecl/issues/474 .

**Comment by kpoeck** [comment]
Fixes the problem and shows no errors either in regression-tests nor in ansi-tests

**Comment by Bike** [comment]
Just as a future note to myself or whoever, this is a general problem with checking initargs for object creation of any kind - the defclass thing is just a consequence.

Anyway, fix looks good to me and I merged it. Thanks a lot, dkochmanski.
