### ISSUE TITLE
Unicode strings are not treated correctly by compile-file

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#723]
Compile/load file the following e.g. in slime
```lisp
(in-package :cl-user)

(defun test ()
  "├─")

````
and than in the repl.
```lisp
(char-code (char (test) 0))
-> 28
````
the result should be 9500 (char-code (char "├─" 0))

**Comment by kpoeck** [comment]
The error is quite clear.
In cmpliteral.lsp in
(defun object-similarity-table-and-creator (object read-only-p) ..)
the following is used.
```lisp
((stringp  object) (values (if read-only-p *identity-coalesce* *string-coalesce*) #'ltv/base-string))
````
ltv/base-string does not preserve unicode-strings. 
While the analysis is clear I don't know how to define e.g. a ltv/unicode-string

**Comment by Bike** [comment]
It occurred to me that we probably don't need to define an `ltv/unicode-string` - the general array constructor should be fine. I'm trying it out now.

Of course, it would probably be more efficient to special case. We'll see.

**Comment by kpoeck** [comment]
And works like a charm
