### ISSUE TITLE
Class machinery fails on some metaclasses with extra slots

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#728]
Reported by kpoeck in relation to loading shimera's Trial library, but can be reproduced as follows:

```
(defclass foo () ((bar :accessor bar)))
(defclass foo-class (standard-class foo) ())
(defclass baz () () (:metaclass foo-class))
```

this last form will result in a type error `#<SHARED-MUTEX CALL-HISTORY-GENERIC-FUNCTIONS-MUTEX @0x11a689009> is not of type SYMBOL.` for whatever address.

The issue is that the C++ code dealing with classes uses fixed class offsets, that is, basically accesses slots with `standard-instance-access` with hardcoded indices. `foo-class` has different slot locations from `standard-class`, and so the C++ code gets bizarre values.

The two solutions I see here are either to have the C++ code go through the regular accessor functions, or to force the slot indices. The former would entail a small (I think) speed hit. I'm going to try the latter, because it shouldn't conflict with anything the user can do, and there's some up-til-now-vestigial code that might make it easy.

**Comment by kpoeck** [comment]
My problem is also fixed by this fix, so we can probably close this
