### ISSUE TITLE
Inferred generic function lambda lists too strict

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#729]
```
(defmethod foo (x &key a))
(defmethod foo ((x integer) &key)
```

with no previous defgeneric results in an error about the lambda-lists being incongruent.

CLHS DEFMETHOD says about its implicit generic function definitions, "if the defmethod form mentions keyword arguments, the lambda list of the generic function will mention ..... key (but no keyword arguments)". We, however, keep the keyword arguments for the generic function lambda list.

Reported by kpoeck in relation to Shinmera's "trial" library.

**Comment by kpoeck** [comment]
Fixed by Bike
