### ISSUE TITLE
Limitation of metaclasses in clasp (and ecl)

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#736]
I believe this is the cause of https://github.com/metawilm/cl-python/issues/23. Also affects trial from shinmera.

Might be undefined behaviour, I remember how that this was discussed in #clasp and people said it is contradictory to other things in the standard. At least I wan't to document the current state.

step1 Define a file metaclass.lisp where your lisp can find it with the following content
```lisp
(in-package :cl-user)
(defclass foo (standard-class)())

(defmethod c2mop:validate-superclass ((class foo) (superclass standard-class))
  T)

(defclass super ()())

(defclass bar (super)()(:metaclass foo))

(defparameter foo-bar (make-instance 'bar))

(print foo-bar)
````
Step2
```lisp
Start your lisp
(load "~/quicklisp/setup.lisp")
(ql:quickload  :closer-mop)
````
Step3 load/compile the above file:
```lisp
(load (compile-file "<adaptyourpath/metaclass.lisp"))
````
Results in different lisps
````
ccl      :fine
sbcl     :fine
clisp    :fine
ecl      :fine
;;; Error:
;;;   in file metaclass.lisp, position 341
;;;   at (DEFCLASS BAR ...)
;;;   * The form (PROGN (PROGN (EXT:OPTIONAL-ANNOTATION 'BAR 'EXT:LOCATION '(DEFCLASS BAR) '(#P"/Users/karstenpoeck/lisp/compiler/clasp/metaclass.lisp" . 341)) NIL (CLOS:LOAD-DEFCLASS 'BAR '(SUPER) NIL (LIST :METACLASS 'FOO)))) was not evaluated successfully.
;;; Error detected:
;;; Class #<The STANDARD-CLASS COMMON-LISP-USER::SUPER> is not a valid superclass for #<The COMMON-LISP-USER::FOO COMMON-LISP-USER::BAR>
Condition of type: TYPE-ERROR
NIL is not of type STREAM.

cmucl    :fine
allegro  :fine
clasp    
Condition of type: SIMPLE-ERROR
Class #<The STANDARD-CLASS COMMON-LISP-USER::SUPER> is not a valid superclass for #<The COMMON-LISP-USER::FOO COMMON-LISP-USER::BAR>
Available restarts:
(use :r1 to invoke restart 1)
````

Workarounds:
* load the source file, than recompile
* split the file in 2, before and after (defclass bar (super)()(:metaclass foo))

**Comment by Bike** [comment]
This is caused by our defining classes pretty fully at compile time. I'm going to call it a bug, though the CLHS is kind of weird on the topic of compile time classes.

**Comment by Bike** [comment]
Just pushed a commit that I think fixes this. clpython still won't load, but it's because of a later problem of unrelated lack of iplementation support for clasp, I believe.

**Comment by kpoeck** [comment]
I have a fork of cl-python that loads fine in clasp, so let me try this with your fix

**Comment by kpoeck** [comment]
Works fine both this example and cl-python, great work!
