### ISSUE TITLE
Funcallable instances don't work with closures

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#739]
```
(defclass mygf (clos:funcallable-standard-object)
  ()
  (:metaclass clos:funcallable-standard-class))
; => #<The CLOS:FUNCALLABLE-STANDARD-CLASS COMMON-LISP-USER::MYGF>

(let ((mygf (make-instance 'mygf)))
  (clos:set-funcallable-instance-function mygf (let ((x 9)) (lambda () x)))
  (funcall mygf))
; => 1141454420
```

I believe this is because we copy the function's entry point into the funcallable instance, but not its closure.

**Comment by Bike** [comment]
@drmeister has fixed this with ead0acad and 40f0e7cb4. This example now returns 9 and from the example in #712 I get `(:boo #<LEXER-BUG NIL> 23)`. @kpoeck, can you confirm?

**Comment by drmeister** [comment]
I fixed funcallable-instances so that you can (set-funcallable-instance-function foo (lambda () ...)).
The code is in 40f0e7cb4fa498d85bdc57b270b98c76cb84b145

**Comment by kpoeck** [comment]
Hello, #712 is also fixed with current changes

**Comment by Bike** [comment]
Alright. Let's hope I don't break this again.
