### ISSUE TITLE
(locally (declare (notinline +)(+ "jd"))) -> nil

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#747]
```lisp
(locally (declare (notinline +)(+ "jd"))) -> nil
(+ "jd")

Condition of type: TYPE-ERROR
"jd" is not of type NUMBER.

(let ()(+ "jd"))
"jd"

````
this is without any local patches
I am puzzeld since I thought (locally (declare (notinline +)(+ "jd")))  would be the same as (+ "jd")

The (let ()(+ "jd")) does not error since 
```lisp
COMMON-LISP-USER>> (funcall (compiler-macro-function '+) '(+ "jd") nil)

(VALUES (THE NUMBER "jd"))
````
and the "(the number ...) is later ignored by cleavir

**Comment by Bike** [comment]
I don't see any nil return value. With the notinline, the compiler macro is suppressed and it calls the actual function, which signals a type error. Without it, you get the `the` form and there's no error because it's not safe code.

**Comment by Bike** [comment]
Wait, there it goes. Must be an evaluator thing then.

**Comment by Bike** [comment]
Oh. The actual problem is that you have
```
(locally
  (declare (notinline +)
                 (+ "jd")))
```

and the interpreter for `locally` ignores the wonky declaration.

**Comment by kpoeck** [comment]
Oops, error sitting in front of the computer
