### ISSUE TITLE
Wrong style-warning

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#770]
```lisp
(compile nil '(lambda(&key (element-type t element-type-p))
  (declare (ignore element-type-p))
  element-type))
; caught STYLE-WARNING:
;   The variable ELEMENT-TYPE was referenced,
;   despite being declared IGNORE.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
#<FUNCTION LAMBDA>
````
element-type-p is not used, but element-type
I believe that was there all the time, just now with improved source tracking I could spot that

**Comment by Bike** [comment]
This is almost certainly actually a bug in Cleavir, so once I figure it out I'll probably move this report there.

**Comment by Bike** [comment]
https://github.com/robert-strandh/SICL/issues/139

i'll update clasp's sicl commit later

**Comment by Bike** [comment]
Should be fixed now.

**Comment by kpoeck** [comment]
Fixed as Bike said
