### ISSUE TITLE
Regression: ansi-test reduce for displaced array accesses out of bounds

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#800]
```lisp
(reduce #'+ (let ((s0 (make-array 5 :initial-contents '(0 1 2 3 4))))
           (make-array 2 :displaced-to s0 :displaced-index-offset 2)))
->
Condition of type: TYPE-ERROR
#\NUL is not of type NUMBER.
````
Tracing vref it shows that it errors after
(VREF #(0 1 2 3 4) 13)

**Comment by kpoeck** [comment]
I believe the error is in do-subvector
with *foo* being the array
(core::do-subvector (var *foo* 0 2)(print var)) loops.
The problem may be that with-array-data transforms the start index in case of an displaced array but the end parameter is not transformed.

That may result in index > %limit in the do loop. so it never terminates

**Comment by Bike** [comment]
I think you're correcting. Testing a fix now. (Also for the `from-end` case, which as a different `do-subvector`.)

**Comment by kpoeck** [comment]
Looks like it should work, building now, will test tonight (UTC+2) when back from work

**Comment by kpoeck** [comment]
works
