### ISSUE TITLE
using symlinks in the include directory for generated files probably won't work for an installation

### ISSUE THREAD

**Issue by fmitha** [clasp-developers/clasp#83]
The current way of having the generated include files in the include directory is to generate them in the main source (as before) and have symlinks (which have been committed in the source) in the include directory.

This approach will probably not work for an installation, and is a bad idea anyway, fo the following obvious reason. When the include directory is copied somewhere else the symlinks will then point nowhere. How bad this is depends on whether the generated include files are actually required. In any case, having broken symlinks is never a good thing.

I'd recommend either have the files generated directly in the include directory in the first place, and adjusting everything to look for them there, or if they are really required in their current location in the main source, an immediate copy could be made at the time of generation.

**Comment by yitzchak** [comment]
We no longer do this. Generated include files are in the build directory.
