### ISSUE TITLE
3 new ansi-test regressions with sequence functions

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#855]
All the following 3 should raise a type error, at least with safe declarations
```lisp
;;; MEMBER-IF.ERROR.8
;;; ASSOC-IF.ERROR.12
;;; ASSOC-IF-NOT.ERROR.12
COMMON-LISP-USER> (declaim (optimize (safety 3)(speed 0)))

((CLASP-CLEAVIR::SAVE-REGISTER-ARGS . T) (CORE::INSERT-ARRAY-BOUNDS-CHECKS . T)
 (CLASP-CLEAVIR::DO-TYPE-INFERENCE) (CLASP-CLEAVIR::DO-DX-ANALYSIS)
 (CLEAVIR-ESCAPE:TRUST-DYNAMIC-EXTENT)
 (CLEAVIR-KILDALL-TYPE-INFERENCE:INSERT-TYPE-CHECKS . T))
COMMON-LISP-USER> (MEMBER-IF #'IDENTITY 'A)
A
COMMON-LISP-USER> (ASSOC-IF #'NULL '((A . B) :BAD (C . D)))
NIL
COMMON-LISP-USER> (ASSOC-IF-NOT #'IDENTITY '((A . B) :BAD (C . D)))
NIL
````

**Comment by kpoeck** [comment]
If I drop the - unproven - (the cons ...) declarations from opt-cons.lisp as in the following, expected behaviour is restored
```lisp
(defmacro do-in-list ((%elt %sublist list &rest output) &body body)
  `(do* ((,%sublist ,list (cdr ,%sublist)))
        ((null ,%sublist) ,@output)
     (let ((,%elt (car ,%sublist)))
       ,@body)))
(defun expand-assoc (env value list &rest sequence-args)
  (multiple-value-bind (key-function test-function init
                        key-flag test-flag test)
      (two-arg-test-parse-args 'assoc sequence-args :start-end nil :environment env)
    (when test-function
      (si::with-unique-names (%value %sublist %elt %car)
        `(let ((,%value ,value)
               ,@init)
           (do-in-list (,%elt ,%sublist ,list)
             (when ,%elt
               (let ((,%car (car ,%elt)))
                 (when ,(funcall test-function %value
                                 (funcall key-function %car))
                   (return ,%elt))))))))))
````
Since MEMBER-IF, ASSOC-IF & ASSOC-IF-NOT are already compiled with base clasp as a user I can't restore safe behaviour.

**Comment by kpoeck** [comment]
Proposed fix would also solve #853.

**Comment by kpoeck** [comment]
To run the ansi-test with current clasp I also had to deactivate these tests:
```lisp
  (rt:rem-test 'cl-test::sublis.error.8)
  (rt:rem-test 'cl-test::nsublis.error.8)
  (rt:rem-test 'cl-test::member-if.4)
  (rt:rem-test 'cl-test::member-if.error.1)
  (rt:rem-test 'cl-test::member-if-not.4)  
  (rt:rem-test 'cl-test::member-if-not.error.1)
  (rt:rem-test 'cl-test::assoc-if.error.11)
  (rt:rem-test 'cl-test::assoc-if.error.13)
  (rt:rem-test 'cl-test::assoc-if-not.error.11)
  (rt:rem-test 'cl-test::assoc-if-not.error.13)
  (rt:rem-test 'cl-test::stable-sort.error.11) 
````
I assume the proposed fix would solve that as well

**Comment by kpoeck** [comment]
rebuilding with the proposed fix solves the 3 errors, so doing a pr for that

**Comment by kpoeck** [comment]
`(funcall #'(lambda (x) (stable-sort x #'<)) #'defun)`
also give a segfault, so test sequence being a vector before calling vector-merge-sort

**Comment by Bike** [comment]
these are probably all basically due to the new transforms i put in, that turn `(car (the cons ...))` into a primitive operation that doesn't do any testing. We should figure out where we can test ahead of time and where we can't. I could make the transforms conditional on safety, too, but actually adding tests is trickier

**Comment by kpoeck** [comment]
But i still believe the declarations are simply untrue, thats why i submitted pr #856. 

All what you said is true, but the declarations might not be correct as the example shows.

**Comment by Bike** [comment]
The declarations are untrue if the programmer calls `assoc` or whatever in a way that violates its type constraints.  If they do so the effects are undefined. Crashing is fine from a conformance perspective.

Obviously we don't generally _want_ to crash despite that, but I think it's reasonable to - provided the safety optimization level is low. Right now we're not provisioning that.

**Comment by kpoeck** [comment]
With low safety all what you say is obviously true, my only concern is with safe code in the sense of 1.4.2 Error Terminology

So I believe for standard compliance the following should signal a type error (which it does)
```lisp
(declaim (optimize (safety 3)(speed 0)))
((CLASP-CLEAVIR::SAVE-REGISTER-ARGS . T) (CORE::INSERT-ARRAY-BOUNDS-CHECKS . T)
 (CLASP-CLEAVIR::DO-TYPE-INFERENCE) (CLASP-CLEAVIR::DO-DX-ANALYSIS)
 (CLEAVIR-ESCAPE:TRUST-DYNAMIC-EXTENT)
 (CLEAVIR-KILDALL-TYPE-INFERENCE:INSERT-TYPE-CHECKS . T))
COMMON-LISP-USER> (let ()(assoc :foo '((A . B) :BAD (C . D))))

Condition of type: TYPE-ERROR
:BAD is not of type CONS.
````

so all fine, but now with assoc-if that calls assoc but was compiled building clasp with lower safety
```lisp
COMMON-LISP-USER> (declaim (optimize (safety 3)(speed 0)))

((CLASP-CLEAVIR::SAVE-REGISTER-ARGS . T) (CORE::INSERT-ARRAY-BOUNDS-CHECKS . T)
 (CLASP-CLEAVIR::DO-TYPE-INFERENCE) (CLASP-CLEAVIR::DO-DX-ANALYSIS)
 (CLEAVIR-ESCAPE:TRUST-DYNAMIC-EXTENT)
 (CLEAVIR-KILDALL-TYPE-INFERENCE:INSERT-TYPE-CHECKS . T))
COMMON-LISP-USER> (let ()(assoc-if #'null '((a . b) . c)))

Condition of type: SEGMENTATION-VIOLATION
Segmentation fault. Attempted to access resticted memory address #x0.

This is due either to a problem in foreign code (e.g., C++), or a bug in Clasp itself.
````
This I understand as non-compliant, since:
14.2.36 assoc, assoc-if, assoc-if-not
says "Should be prepared to signal an error of type type-error if alist is not an association list."

For sure there are various solutions to that problem:
* what I proposed
* build clasp with (optimize (safety 3))
* make transforms conditional on safety (but safety at run-time or at compile-time)

**Comment by Bike** [comment]
You're right, `assoc-if` crashing on safety 3 due to bad types is noncompliant.

I'll try making crashable transformations conditional on safety 0. We build ourselves on safety 1, so the use of `assoc` within the definition of `assoc-if` should avoid those transformations.

**Comment by Bike** [comment]
Done. I'm back to getting a type error.

**Comment by kpoeck** [comment]
Bike that does not seem to work and I believe it can't work.
```lisp
COMMON-LISP-USER> (declaim (optimize (safety 3)(speed 0)))

((CLASP-CLEAVIR::SAVE-REGISTER-ARGS . T) (CORE::INSERT-ARRAY-BOUNDS-CHECKS . T)
 (CLASP-CLEAVIR::TRUST-TYPE-DECLARATIONS) (CLASP-CLEAVIR::DO-TYPE-INFERENCE)
 (CLASP-CLEAVIR::DO-DX-ANALYSIS) (CLEAVIR-ESCAPE:TRUST-DYNAMIC-EXTENT)
 (CLEAVIR-KILDALL-TYPE-INFERENCE:INSERT-TYPE-CHECKS . T))
COMMON-LISP-USER> (MEMBER-IF #'IDENTITY 'A)

A
COMMON-LISP-USER> (ASSOC-IF #'NULL '((A . B) :BAD (C . D)))

NIL
COMMON-LISP-USER> (ASSOC-IF-NOT #'IDENTITY '((A . B) :BAD (C . D)))
NIL
```` 

and why should it work, member-if, assoc.if and assoc-if-not are long compiled when I do (declaim (optimize (safety 3)(speed 0)))

For it to work, I need to recompile member-if, assoc.if and assoc-if-not:
```lisp
COMMON-LISP-USER> (load (compile-file "sys:kernel;lsp;listlib.lsp"))
; Compiling file: /Users/karstenpoeck/lisp/compiler/clasp-karsten/src/lisp/kernel/lsp/listlib.lsp
;   (IN-PACKAGE "SYSTEM")
;   (DEFMACRO APPLY-KEY ...)
;   (DEFUN UNION ...)
;   (DEFUN NUNION ...)
;   (DEFUN ADJOIN ...)
;   (DEFUN INTERSECTION ...)
;   (DEFUN NINTERSECTION ...)
;   (DEFUN SET-DIFFERENCE ...)
;   (DEFUN NSET-DIFFERENCE ...)
;   (DEFUN SWAP-ARGS ...)
;   (DEFUN SET-EXCLUSIVE-OR ...)
;   (DEFUN NSET-EXCLUSIVE-OR ...)
;   (DEFUN SUBSETP ...)
;   (DEFUN RASSOC-IF ...)
;   (DEFUN RASSOC-IF-NOT ...)
;   (DEFUN ASSOC-IF ...)
;   (DEFUN ASSOC-IF-NOT ...)
;   (DEFUN MEMBER-IF ...)
;   (DEFUN MEMBER-IF-NOT ...)
;   (DEFUN SUBST ...)
;   (DEFUN SUBST-IF ...)
;   (DEFUN SUBST-IF-NOT ...)
;   (DEFUN NSUBST-IF ...)
;   (DEFUN NSUBST-IF-NOT ...)
;   (DEFUN NSUBST ...)
;   (DEFUN NSUBST-AUX ...)
Writing temporary bitcode file to: #P"SYS:KERNEL;LSP;LISTLIB.BC.NEWEST"
Writing fasl file to: #P"SYS:KERNEL;LSP;LISTLIB.FASL.NEWEST"
T
COMMON-LISP-USER> (MEMBER-IF #'IDENTITY 'A)

Condition of type: TYPE-ERROR
A is not of type CONS.

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[0] NIL. In: #<PROCESS TOP-LEVEL @0x10c107719>.
;;; Warning: compiled-function-file expected a function as argument - but it got NIL - there may not be any backtrace available
COMMON-LISP-USER>> :r1

COMMON-LISP-USER> (ASSOC-IF #'NULL '((A . B) :BAD (C . D)))

Condition of type: TYPE-ERROR
:BAD is not of type CONS.

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[0] NIL. In: #<PROCESS TOP-LEVEL @0x10c107719>.
;;; Warning: compiled-function-file expected a function as argument - but it got NIL - there may not be any backtrace available
COMMON-LISP-USER>> :r1

COMMON-LISP-USER> (ASSOC-IF-NOT #'IDENTITY '((A . B) :BAD (C . D)))

Condition of type: TYPE-ERROR
:BAD is not of type CONS.

Available restarts:
(use :r1 to invoke restart 1)
````

**Comment by kpoeck** [comment]
I strongly believe If the decision about the safe/unsafe code is made at compile-time, it cannot work

**Comment by Bike** [comment]
I just built dev and started a fresh image and I'm getting type errors, even without your declaim optimize. I don't understand how you're seeing what you are.

The unsafe transforms are now only applied if safety is zero, which it is not during the build process, so e.g. when `assoc-if` is built the definition is fine (i.e. the type declarations are ignored).

**Comment by Bike** [comment]
And I mean... safety is determined at compile time by definition. We just need to make sure that actual function definitions are safe (i.e. during build they're compiled safely), since they can be called in safe code. And that's what my change does. (Technically it doesn't make them CLHS "safe code", but makes them safe enough)

**Comment by kpoeck** [comment]
Ok, let me re-start testing with distclean. As you said that should work fine, if during the build  they're compiled safely

**Comment by kpoeck** [comment]
and works after distclean, even ansi-tests complete
