### ISSUE TITLE
Question: How do we INSTALL clasp?

### ISSUE THREAD

**Issue by rpgoldman** [clasp-developers/clasp#861]
I have successfully built clasp, but now I don't see how to install it. I'm afraid I don't understand how `waf` works.

What I expected was to configure with an install prefix (in my case, `/usr/local/stow/clasp`) and then be able to do `make install` or possibly `waf install`.  But I don't see any instructions for anything like that, nor do I see a list of files that need to be moved into place in order to do such an install.

I could quite easily have missed something; if so, apologies in advance.

**Comment by kpoeck** [comment]
Will check for installation in the wscript but in the meantim to start simply use build/clasp

**Comment by kpoeck** [comment]
after consulting with drmeister:
to install
 ./waf install_cboehm
goes to /usr/local/bin/clasp

To change the prefix,
optionally ./waf distclean 
./waf configure --prefix="/your/path"
./waf build_cboehm
./waf install_cboehm

**Comment by rpgoldman** [comment]
Thanks.  That was helpful.  One suggestion:

`waf --help`

does not print the commands that are actually implemented.  E.g., `waf --help` describes `waf build`, but says nothing about `waf build_cboehm`.  It might be helpful to update the help strings.

**Comment by kpoeck** [comment]
Will do if I find out how to do so :-)

**Comment by drmeister** [comment]
I see how to add options to the ./waf --help output but not commands.  
I'll make ./waf build do the default right thing.:  ./waf build_cboehm
I'll make install do the right thing as well.   ./waf install_cboehm

Note: You set up where the install goes with: ./waf configure --prefix=path-to-install-to

**Comment by drmeister** [comment]
Wow - ok, I can't do that.
I'll have to dig through the documentation to figure out how to fix the documentation.

**Comment by rpgoldman** [comment]
> I see how to add options to the ./waf --help output but not commands.
> I'll make ./waf build do the default right thing.: ./waf build_cboehm
> I'll make install do the right thing as well. ./waf install_cboehm
> 
> Note: You set up where the install goes with: ./waf configure --prefix=path-to-install-to

Thanks!  That "make install" worked for me.

**Comment by rpgoldman** [comment]
I added a `make install`.  See #909 for patch file.

**Comment by kpoeck** [comment]
#973 should implement make install

**Comment by kpoeck** [comment]
Fix merged
