### ISSUE TITLE
Package iterate fails to load

### ISSUE THREAD

**Issue by yitzchak** [clasp-developers/clasp#863]
The iterate package fails on compiling with `L is not a sub-character of the dispatch macro character #.` 

Maybe CLASP is not evaluating [eval-when](https://gitlab.common-lisp.net/iterate/iterate/blob/master/iterate.lisp#L461) before `walk` is defined?

[session.txt](https://github.com/clasp-developers/clasp/files/3693760/session.txt)

**Comment by yitzchak** [comment]
I've managed to narrow this down to the following minimal example saved as `test.lisp`

```common-lisp
(eval-when (:compile-toplevel :execute)
  (defun dollar-reader (stream subchar arg)
    (declare (ignore subchar arg))
    (list 'print (read stream t nil t)))
  (set-dispatch-macro-character #\# #\$ #'dollar-reader))

#$1
```

Both `load` and `compile-file` work on SBCL, CCL AND ABCL. Only `load` works on CLASP. `compile-file` gives

```
Condition of type: UNKNOWN-MACRO-SUB-CHARACTER
$ is not a sub-character of the dispatch macro character #.
```

**Comment by kpoeck** [comment]
No, this is symptom of the incomplete integration of eclector.

Works fine if you disable cst or apply https://github.com/clasp-developers/clasp/wiki/Properly-integrate-eclector-into-clasp

**Comment by yitzchak** [comment]
Okay, thanks.
