### ISSUE TITLE
Regression EQUALP-7 (clasp regression-tests)

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#869]
```lisp
(let ((vector (make-array 3 :fill-pointer 2 :initial-contents (list 1 2 3))))
        (equalp vector (copy-seq vector)))
````
fails, but used to return t

**Comment by kpoeck** [comment]
I believe this fails here (old code not changed in the recent restructering)
https://github.com/clasp-developers/clasp/blob/dev/include/clasp/core/array.h#L755

If I understand the definition of equalp right, it says "The types for which the arrays are specialized need not match", so perhaps this code is wrong and should be like the code in MDArray_O::equalp
```c++
  if (!other.generalp()) return false;
  if (!gc::IsA<Array_sp>(other)) return false;
  Array_sp aother = gc::As_unsafe<Array_sp>(other);
````

Before the restructering of the code MDArray_O::equalp was called for the above lisp form, and this worked well.

**Comment by Bike** [comment]
Er, element types don't matter here, do they? The problem is that it's ignoring the fill pointer - the original has length 3, but the simple copy has length 2.

**Comment by Bike** [comment]
I just deleted the equalp method in `template_Vector` and I get T again, so I'll push in a minute.

**Comment by Bike** [comment]
Oh I see what you meant, it's the `asOrNull<my_array_type>()` that screws things up, and then even if that passed the array dimension thing would be a problem. Cool, good, definitely just getting rid of this code entirely

**Comment by kpoeck** [comment]
Deleting the equalp In template_vector sounds right

**Comment by kpoeck** [comment]
fixed
