### ISSUE TITLE
Regression: several ansi-tests for displaced arrays fail

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#873]
The following tests all fail now:
`MAKE-ARRAY.DISPLACED.17, MAKE-ARRAY.DISPLACED.18, 
   MAKE-ARRAY.DISPLACED.20, MAKE-ARRAY.DISPLACED.22, 
   MAKE-ARRAY.DISPLACED.23, MAKE-ARRAY.DISPLACED.24, 
   MAKE-ARRAY.DISPLACED.25, MAKE-ARRAY.DISPLACED.26`

I think they all all have the same pattern like this test:
```lisp
(equalp #(1 2 3 4 5 6 7 8)
        (LET ((A
               (MAKE-ARRAY '(3 4)
                           :INITIAL-CONTENTS
                           '((1 2 3 4) (5 6 7 8) (9 10 11 12)))))
          (MAKE-ARRAY 8 :DISPLACED-TO A)))
nil
````
note that the following works fine:
```lisp
(equalp #(1 2 3 4 5 6 7 8)
        (LET ((A
               (MAKE-ARRAY 12
                           :INITIAL-CONTENTS
                           '(1 2 3 4 5 6 7 8 9 10 11 12))))
          (MAKE-ARRAY 8 :DISPLACED-TO A)))
T
````

so the error might be if a 1-dimensional array is displaced to 2-dimensional array

**Comment by kpoeck** [comment]
checking with lldb the following seems to happen:
The equalp code being executed is:
https://github.com/clasp-developers/clasp/blob/dev/src/core/array.cc#L716.
in https://github.com/clasp-developers/clasp/blob/dev/src/core/array.cc#L731
the code fails (values from the failing example)
* this->rowMajorAref(0) returns 1 (tagged) and
* mdother->rowMajorAref(0) returns 3 (tagged)

Calling with a array displaced to a array with dimensions 4 * 4,mdother->rowMajorAref(0)  returns 4, so probably mdother->rowMajorAref(0) returns the first dimension and the the first element

**Comment by kpoeck** [comment]
row-major-aref from lisp works fine, but it doesn't call C++ rowMajorAref anymore

**Comment by Bike** [comment]
I saw similar `rowMajorAref` problems last week. Might be because I changed the class hierarchy so the complex vector classes are actually subclasses of `ComplexVector_O`?

**Comment by Bike** [comment]
I think this is because of my putting `ComplexVector_O` in the hierarchy more. `operator[]` for `template_Array` does various type checks but I don't think it can deal with complex vectors.

**Comment by kpoeck** [comment]
fixed
