### ISSUE TITLE
Integer overflow in LOOP

### ISSUE THREAD

**Issue by phoe** [clasp-developers/clasp#874]
Copied from https://gitlab.com/embeddable-common-lisp/ecl/issues/528 verbatim, since @Bike says that it does affect Clasp in exactly the same way.

-----------

ECL from current git master causes integer overflow in safe code inside `LOOP`.

```common-lisp
> (declaim (optimize (safety 3)))
((OPTIMIZE (SAFETY 3)))

> (compile nil (lambda ()
    (loop for x of-type fixnum
          from (1- most-positive-fixnum) to most-positive-fixnum
          do (progn)
          finally (print x))))

;;; OPTIMIZE levels: Safety=3, Space=0, Speed=3, Debug=0
;;;
;;; End of Pass 1.
#<compiled-function 0x555ccc1614c0>
NIL
NIL
> (funcall *)

-2305843009213693952 
```

This is likely due to `ext:assume-right-type` declaration used in macro `loop-unsafe`.

```common-lisp
> (declaim (optimize (safety 3)))
((OPTIMIZE (SAFETY 3)))

> (compile nil (lambda () (let ((x most-positive-fixnum)) (declare (fixnum x)) (locally (declare (ext:assume-right-type)) (setq x (1+ x))))))
;;; OPTIMIZE levels: Safety=3, Space=0, Speed=3, Debug=0
;;;
;;; End of Pass 1.
#<compiled-function 0x555ccc118c40>
NIL
NIL

> (funcall *)
-2305843009213693952
```

This is directly related to [ANSI-TEST `LOOP.1.40`](https://gitlab.common-lisp.net/ansi-test/ansi-test/blob/master/iteration/loop1.lsp#L207) that ECL currently fails:

```common-lisp
;;; Test that the index variable achieves the inclusive
;;; upper bound, but does not exceed it.
(deftest loop.1.40
  (loop for x from 1 to 5 do (progn) finally (return x))
  5) ;; ECL returns 6 instead
```

And to [ANSI-TEST `LOOP.1.39`](https://gitlab.common-lisp.net/ansi-test/ansi-test/blob/master/iteration/loop1.lsp#L200) that, I assume, was meant to be fixed by introducing the `LOOP-UNSAFE` macro:

```common-lisp
;;; The following provides an example where an incorrect
;;; implementation will assign X an out-of-range value
;;; at the end.
(deftest loop.1.39
  (loop for x of-type (integer 1 5) from 1 to 5 collect x)
  (1 2 3 4 5)) ;; ECL passes this test, but X is internally set to an out-of-range value
```

[The CLHS says:](http://www.lispworks.com/documentation/HyperSpec/Body/06_abaa.htm)

> In an iteration control clause, the for or as construct causes termination when the supplied limit is reached. That is, iteration continues until the value var is stepped to the exclusive or inclusive limit supplied by form2.

> For these clauses, iteration terminates when a local variable reaches some supplied value or when some other loop clause terminates iteration.

Rationale: https://gist.github.com/phoe/335fecfdc195bddd47ab0928b0e62e52

**Comment by Bike** [comment]
Now that I actually have a Clasp around, I see that I actually get 2305843009213693952 (i.e. `(1+ most-positive-fixnum)`), which still violates the type declaration.

**Comment by phoe** [comment]
Note: I got comments that suggest  that `of-type fixnum` is invalid in that case and it might be a user error to specify that there. Note https://gist.github.com/phoe/335fecfdc195bddd47ab0928b0e62e52

**Comment by kpoeck** [comment]
With safety 3 I get a nice type-error t runtime.
```lisp
COMMON-LISP-USER> (declaim (optimize (safety 3)))

((CLASP-CLEAVIR::SAVE-REGISTER-ARGS . T) (CORE::INSERT-ARRAY-BOUNDS-CHECKS . T)
 (CLASP-CLEAVIR::TRUST-TYPE-DECLARATIONS) (CLASP-CLEAVIR::DO-TYPE-INFERENCE)
 (CLASP-CLEAVIR::DO-DX-ANALYSIS) (CLEAVIR-ESCAPE:TRUST-DYNAMIC-EXTENT)
 (CLEAVIR-KILDALL-TYPE-INFERENCE:INSERT-TYPE-CHECKS . T))
COMMON-LISP-USER> (compile nil (lambda ()
    (loop for x of-type fixnum
          from (1- most-positive-fixnum) to most-positive-fixnum
          do (progn)
          finally (print x))))

#<FUNCTION LAMBDA>
NIL
NIL
COMMON-LISP-USER> (funcall *)

Condition of type: TYPE-ERROR
2305843009213693952 is not of type (AND (AND (INTEGER -2305843009213693952 2305843009213693951))).

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
````

**Comment by phoe** [comment]
After some discussion, the related ANSI-TESTs were annotated with :ANSI-SPEC-PROBLEM since the spec is not clear on the values of iteration variables or whether they are allowed to overstep their limit. This means that the `TYPE` proclamation there might not be valid.
https://gitlab.common-lisp.net/ansi-test/ansi-test/merge_requests/23
