### ISSUE TITLE
regression: nreverse on bitarrays seem to fail

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#879]
```lisp
CL-USER> (nreverse (copy-seq #*0011))
#*1000
CL-USER> (NREVERSE (COPY-SEQ #*0001101101))
#*1000000000
CL-USER> (NREVERSE (COPY-SEQ #*000110110110))
#*000000000000
CL-USER>   (let* ((x (make-array 10 :initial-contents '(0 0 0 1 1 0 1 0 1 0)
                        :fill-pointer 5
                        :element-type 'bit))
         (y (nreverse x)))
    y)
#*10000
````
all examples give wrong results.

This is nreverse-bit-vector.2 and nreverse-bit-vector.3 in ansi-tests

**Comment by kpoeck** [comment]
Perhaps templated_swapElements does not work fine?

**Comment by kpoeck** [comment]
PErhaps the same problem:
```lisp
(equalp
  #(-1 0 -1 -1 0 -1 0 0)
(nreverse 
 (MAKE-ARRAY 8 :ELEMENT-TYPE '(INTEGER -1 0) :INITIAL-CONTENTS #(0 0 -1 0 -1 -1 0 -1))))
nil
CL-USER> (nreverse 
 (MAKE-ARRAY 8 :ELEMENT-TYPE '(INTEGER -1 0) :INITIAL-CONTENTS #(0 0 -1 0 -1 -1 0 -1)))
#(-1 0 0 0 0 0 0 0)
````
This is ansi nreverse-vector.8

**Comment by Bike** [comment]
`(integer -1 0)` probably upgrades to like, `(signed-byte 2)` now?

Bit vectors should be using the same nreverse as everything else now, so `operator[]` or something could be screwed up

**Comment by Bike** [comment]
Okay, the good news is that these all seem to be consistent, so at least we're probably not copying out of uninitialized memory or some horrible shit like that.

It only seems to be copying the low bit. Probably it's using the wrong length or something...

**Comment by Bike** [comment]
I stepped through it and it _looks_ like it does the correct number of iterations and the masks are correct. The length is correct. Kind of hard to understand all the details though...

**Comment by Bike** [comment]
here is the problem https://github.com/clasp-developers/clasp/blob/4aa5fef906a1535a9952d2dabc950e0bd63dec1f/include/clasp/gctools/gcbitarray.h#L201

as you can see from the similar code in `operator=(value_type)` above, it should be `~(bit_unit_mask << offset)`, not `~(bit_unit_mask) << offset`

fixin

**Comment by kpoeck** [comment]
solved
