### ISSUE TITLE
Warning error with Typep on errors

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#882]
```lisp
COMMON-LISP-USER> (defun foo (array)
  (if (typep array '(ARRAY EXT:BYTE4 (5)))
      (aref array 2)
      23))
; caught WARNING:
;   ERROR during compiler-macro-expansion:
;     BUT: Unknown UAET BYTE4 in SIMPLE-VECTOR-TYPE
;   (Using original form instead.)
; 
; compilation unit finished
;   caught 1 WARNING condition
````

real error happens while compiling retrospectiff with quicklisp (possibly with (optimize (debug 3))
```lisp
;   (DEFUN MAKE-TIFF-IMAGE-FOR-OUTPUT ...)
.....; caught WARNING:
;   ERROR during compiler-macro-expansion:
;     BUT: Unknown UAET BYTE4 in SIMPLE-VECTOR-TYPE
;   (Using original form instead.)
;     at /Users/karstenpoeck/quicklisp/dists/quicklisp/software/retrospectiff-20171019-git/retrospectiff2.lisp 476:2
; 
.; caught ERROR:
;   BUT: Unknown UAET BYTE4 in SIMPLE-VECTOR-TYPE

Condition of type: SIMPLE-ERROR
BUT: Unknown UAET BYTE4 in SIMPLE-VECTOR-TYPE

Available restarts:
(use :r1 to invoke restart 1)

1. (RETRY) Retry compiling #<CL-SOURCE-FILE "retrospectiff" "retrospectiff2">.
2. (ACCEPT) Continue, treating compiling #<CL-SOURCE-FILE "retrospectiff" "retrospectiff2"> as having been successful.
3. (RETRY) Retry ASDF operation.
4. (CLEAR-CONFIGURATION-AND-RETRY) Retry ASDF operation after resetting the configuration.
5. (RETRY) Retry ASDF operation.
6. (CLEAR-CONFIGURATION-AND-RETRY) Retry ASDF operation after resetting the configuration.
7. (ABORT) Give up on "mcclim"
8. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
````

**Comment by Bike** [comment]
Easy to fix.

To be clear, asdf is just seeing a warning, which fails the compilation. If the error was escaping the compiler macro function that would be a new problem.

**Comment by kpoeck** [comment]
Thats explains that in the code an error was raised, but a warning was given. 

I always get confused about the second value failure-p returned by compile-file. In the spec it says, it returns t, if an error or warning (not style warning) was generated. That a  compilation counts as failed, when a warning was produced is counterintuitive for me.

as far as I know, the following produces a warning, so asdf will error
(defun test ())
(defun test ())

**Comment by kpoeck** [comment]
the fix looks obvious now that you have written it :-)

**Comment by Bike** [comment]
warnings are for when the code will have undefined effects or suchlike. multiple functions with the same name in the same file is undefined for compile-file.

**Comment by kpoeck** [comment]
Issue fixed as promised
