### ISSUE TITLE
Regression: search for strings fails 

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#887]
```lisp
;;;Wrong, expected answer 1
COMMON-LISP-USER> (search "1" "213")
NIL
;;; ok
COMMON-LISP-USER> (search "1" "123")
0
````

This is regression test SEARCH-SEQUENCE-1

**Comment by Bike** [comment]
i suspect this is because i removed some sequence_start_end calls in `core:search-string`. I don't quite remember why though. guess i can learn

**Comment by Bike** [comment]
In 7331a1908a594ec9b569ebcfa3c6626ff8ce07da. Because I moved it to using `core:sequence-start-end` instead of `sequenceStartEnd` like it was using. And they're completely different functions. Super

**Comment by kpoeck** [comment]
Fixed
