### ISSUE TITLE
Regression:char-* functions via compiler macro don't type error if a hash-table is pased as an argument

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#889]
See
```lisp
(let ()
  (and
   (CHAR= (make-hash-table))
   (CHAR/= (make-hash-table))
   (CHAR< (make-hash-table))
   (CHAR> (make-hash-table))
   (CHAR<= (make-hash-table))
   (CHAR>= (make-hash-table))
   (CHAR-LESSP (make-hash-table))
   (CHAR-GREATERP (make-hash-table))
   (CHAR-EQUAL (make-hash-table))
   (CHAR-NOT-LESSP (make-hash-table))
   (CHAR-NOT-GREATERP (make-hash-table))
   (CHAR-NOT-EQUAL (make-hash-table))))
--> t
````

but
```lisp
(progn
  (and
   (CHAR= (make-hash-table))
   (CHAR/= (make-hash-table))
   (CHAR< (make-hash-table))
   (CHAR> (make-hash-table))
   (CHAR<= (make-hash-table))
   (CHAR>= (make-hash-table))
   (CHAR-LESSP (make-hash-table))
   (CHAR-GREATERP (make-hash-table))
   (CHAR-EQUAL (make-hash-table))
   (CHAR-NOT-LESSP (make-hash-table))
   (CHAR-NOT-GREATERP (make-hash-table))
   (CHAR-NOT-EQUAL (make-hash-table))))
->
Condition of type: TYPE-ERROR
#<HASH-TABLE-EQL :HashTableCount 0 :calculated-entries 0 :size 16 @0x1268fac18> is not of type CHARACTER.

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[0] NIL. In: #<PROCESS TOP-LEVEL @0x114a52a19>.
;;; Warning: compiled-function-file expected a function as argument - but it got NIL - there may not be any backtrace available

````

**Comment by kpoeck** [comment]
Used to error just for CHAR=  and CHAR/= but now errors for the other functions as well

**Comment by kpoeck** [comment]
I believe the error is twofold:
* expand-compare expands for 1 arg just into (progn (the ,arg-type ,(first args)) t)
* (the type value) does nothing is cst, see #765 
* same workaround as in #765 would help here

**Comment by kpoeck** [comment]
Recompiling expand-compare with (declaim (optimize (speed 0)(safety 3))) solves the issue. I believe again the problem is, what kind of optimisations should clasp apply in its own core, or perhaps more specifically under which circumstances a 'the declaration can be ignored in claspsown core.

If the user runs unsafe code, he is on his own, but here the user has no way to have high safety respected.

**Comment by kpoeck** [comment]
Digging a bit more, I believe I thing in question is cleavir-kildall-type-inference:insert-type-checks.

So I am pitching that the following should return true while clasp-core is compiled.
```lisp
(defmethod cleavir-policy:compute-policy-quality
    ((quality (eql 'cleavir-kildall-type-inference:insert-type-checks))
     optimize
     (environment clasp-cleavir::clasp-global-environment))
  (> (cleavir-policy:optimize-value optimize 'safety)
     (cleavir-policy:optimize-value optimize 'speed)))
`````
e.g. by putting (safety 2) in the default optimization settings

**Comment by Bike** [comment]
i think i'm content to let this one in particular fester for a bit, until we have an actual plan for dealing with type safety

**Comment by Bike** [comment]
since the THE changes you now get errors if you put in `optimize safety`.

**Comment by kpoeck** [comment]
seam to work with
`(declaim (optimize (safety 2)))`or
`(declaim (optimize (safety 3)))`
