### ISSUE TITLE
regression ansi-tests: (make-sequence 'symbol 10) no longer returns type-error

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#890]
```lisp
(make-sequence 'symbol 10)
Debugger received error of type: NO-APPLICABLE-METHOD-ERROR
No applicable method for ALLOCATE-INSTANCE with arguments
 (#<The BUILT-IN-CLASS SYMBOL>)
(make-sequence 'hash-table 10)
....
````

**Comment by kpoeck** [comment]
I believe this is mandated by clhs 17.3.5 make-sequence
An error of type type-error must be signaled if the result-type is neither a recognizable subtype of list, nor a recognizable subtype of vector.

**Comment by kpoeck** [comment]
that is MAKE-SEQUENCE.ERROR.1 & MAKE-SEQUENCE.ERROR.14,

**Comment by kpoeck** [comment]
same with 
```lisp
(map 'symbol #'identity '(a b c))
Debugger received error of type: NO-APPLICABLE-METHOD-ERROR
No applicable method for ALLOCATE-INSTANCE with arguments
 (#<The BUILT-IN-CLASS SYMBOL>)
Error flushed.
````

**Comment by kpoeck** [comment]
Ansi MAP.ERROR.1, MAP.ERROR.1A

**Comment by Bike** [comment]
Let's see. The cmacro on `make-sequence` now defers to `sequence:make-sequence`, which does various runtime stuff. We can have it check that the class it's given is actually a sequence class. And as an extra we could have `make-sequence` give up immediately if the class is definitely not a sequence.

**Comment by kpoeck** [comment]
fixed
