### ISSUE TITLE
regression ansi-tests: (coerce nil 'cons) no longer errors

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#892]
```lisp
COMMON-LISP-USER> (typep nil 'cons)
NIL
COMMON-LISP-USER> (coerce nil 'cons)
NIL
````
This is COERCE.ERROR.4 & COERCE.ERROR.9

**Comment by Bike** [comment]
this basically comes down to `make-sequence` and `concatenate` and so on signaling type errors

which is such a dumb requirement, but whatevs, should be able to fix this today

**Comment by kpoeck** [comment]
fixed
