### ISSUE TITLE
Compiling sbcl: perhaps incorrect warning in make-array?

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#910]
After Bike's defstruct fix with :include compilation works a lot further: It stops with compiling "src/code/specializable-array.lisp" since the following warning is created:
```lisp
; caught WARNING:
;   ERROR during compiler-macro-expansion:
;     The key (IF CONTENTSP :INITIAL-CONTENTS :INITIAL-ELEMENT) is not allowed
;   (Using original form instead.)
`````

This can be reproduced by compiling
```lisp
COMMON-LISP-USER> (defun test (element-type contentsp initial-contents initial-element dims)
  (cl:make-array
   dims
   :element-type element-type
   (if contentsp :initial-contents :initial-element)
   (if contentsp initial-contents initial-element)))
; caught WARNING:
;   ERROR during compiler-macro-expansion:
;     The key (IF CONTENTSP :INITIAL-CONTENTS :INITIAL-ELEMENT) is not allowed
;   (Using original form instead.)
; 
; compilation unit finished
;   caught 1 WARNING condition
````
The form seem totally fine, so is this perhaps a wrong assumption in the compiler macro?

**Comment by Bike** [comment]
The lambda list parsing in compiler macros generally is wrong, yes. That is, it should give up without any signals passing out of the compiler like this. Here is a simple example not using make-array.

(defun foo (&key bar) bar)
(define-compiler-macro foo (&key bar) bar)
(let () (foo (if t :bar :allow-other-keys) 7))
; caught WARNING:
;   ERROR during compiler-macro-expansion:
;     The key (IF T :BAR :ALLOW-OTHER-KEYS) is not allowed
;   (Using original form instead.)
; 
; compilation unit finished
;   caught 1 WARNING condition
7

**Comment by Bike** [comment]
First solution I can think of would be as follows: Make sure all these sorts of conditions have a common superclass. Put something in translate.lisp to handle this condition with silence. I think cleavir already has the requisite restarts.

**Comment by Bike** [comment]
Hm, that might not be good if it's due to an internal call though.

I thought that an error by a compiler macro ought to be a warning because it would indicate the compiler macro had a problem and probably ought to be debugged. In this particular case there is no problem but now I'm not sure how to recognize that. Maybe we could change the compiler-macro-function body to parse the keys more carefully, and give up silently.

**Comment by Bike** [comment]
should be good now

**Comment by Bike** [comment]
Or it will be after one more commit. Whoopsie.
