### ISSUE TITLE
Error in complex format The variable CORE::ORIG-ARGS is unbound.

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#911]
From cross-compiling sbcl:
```lisp
(defun print-symbol-with-prefix (stream symbol &optional colon at)
  "For use with ~/: Write SYMBOL to STREAM as if it is not accessible from
  the current package."
  (declare (ignore colon at))
  (let ((*package* (find-package :keyword)))
    (write symbol :stream stream :escape t)))

(let ((count 42)
      (function 'print))
  (format t
          "~@<~@(~D~) call~:P to ~
               ~/print-symbol-with-prefix/ ~
               ~2:*~[~;was~:;were~] compiled before a compiler-macro ~
               was defined for it. A declaration of NOTINLINE at the ~
               call site~:P will eliminate this warning, as will ~
               defining the compiler-macro before its first potential ~
               use.~@:>"
          count
          function))
->
; caught WARNING:
;   Undefined variable ORIG-ARGS
; caught WARNING:
;   Undefined variable ORIG-ARGS
; caught WARNING:
;   Undefined variable ORIG-ARGS
; caught WARNING:
;   Undefined variable ORIG-ARGS
; caught WARNING:
;   Undefined variable ORIG-ARGS
; caught WARNING:
;   Undefined variable ORIG-ARGS
; caught WARNING:
;   Undefined variable ORIG-ARGS
; caught WARNING:
;   Undefined variable ORIG-ARGS
; 
; compilation unit finished
;   caught 8 WARNING conditions

Condition of type: UNBOUND-VARIABLE
The variable CORE::ORIG-ARGS is unbound.
````

This is from crosscompiling sbcl, 

https://github.com/sbcl/sbcl/blob/master/src/compiler/ir1report.lisp#L442

**Comment by kpoeck** [comment]
Obviously from kernel/lsp/format.lsp.
Perhaps https://github.com/clasp-developers/clasp/blob/dev/src/lisp/kernel/lsp/format.lsp#L1254

**Comment by Bike** [comment]
Reduced to `(format t "~@<~d call~:P~@:>" 42)`. The compiler macro is not expanding correctly.

**Comment by Bike** [comment]
The problem is that `expand-format-logical-block` does not work correctly with the at sign modifier. Not sure of the details here. The logical block format directive with the at sign modifier is supposed to consume the entire rest of the argument list, but with the first pass in `%formatter-guts` we're saying there is no list. I'm not sure if it should immediately give up though.

**Comment by Bike** [comment]
Our definition of `expand-format-logical-block` differs from sbcl's. sbcl's binds `*orig-args-available*` to `(if atsignp *orig-args-available* t)` rather than just `t`. Commit is [here](https://github.com/sbcl/sbcl/commit/479ef26343b45753fc019b6535d3aa0ee54cb324). Probably we can just mimic them.

**Comment by kpoeck** [comment]
Yes, that change solve the problem, great catch!

Will rebuild and run the regressions to test it

**Comment by kpoeck** [comment]
and add a regression test

**Comment by kpoeck** [comment]
Did test all fine with Bikes fix

**Comment by Bike** [comment]
you can file a pull request or i can change it

**Comment by kpoeck** [comment]
I have 2 more changes to format, so will file a pr

**Comment by kpoeck** [comment]
fixed
