### ISSUE TITLE
Unknown initialization options (:CST) for class #<The STANDARD-CLASS CLEAVIR-ENVIRONMENT:NO-BLOCK-INFO>

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#923]
While compiling:
```lisp
(defun foo ()
  (unless token
      (return (values nil nil))))
 caught WARNING:
;   Undefined variable TOKEN
; caught ERROR:
;   Unknown initialization options (:CST) for class #<The STANDARD-CLASS CLEAVIR-ENVIRONMENT:NO-BLOCK-INFO>.
````

Was a serious typo in the original.
The error seems to be in cleavir:
https://github.com/robert-strandh/SICL/blob/master/Code/Cleavir/CST-to-AST/convert-special.lisp#L67
:cst is not a valid argument to cleavir-env:no-block-info

Seems that :name and :origin must be used instead

**Comment by kpoeck** [comment]
Obviously my code is iilegal, snce no block nil is established to return from

**Comment by Bike** [comment]
ahhhhh yeah i've actually known about this for a while but haven't gotten around to fixing it... i can do that. indeed we just need to pass `:name` and `:origin` instead, or change the condition to have a CST

**Comment by kpoeck** [comment]
fixed in cleavir
