### ISSUE TITLE
unwind-protect not preserving values during unwind correctly

### ISSUE THREAD

**Issue by Bike** [clasp-developers/clasp#948]
I had the `unwind-protect` code using the same value save - call cleanup - value load procedure for both normal and abnormal return. This is not correct. During normal return we have the primary value and number of return values from the protected form saved. During abnormal return there is no such thing, and we just need to preserve the values in the multiple value vector.

This specifically causes problems if something in the cleanup code happens to mess with the multiple value vector. For example, at the moment, C++ function calls returning zero values set the multiple value vector's count to zero.

**Comment by drmeister** [comment]
Here's a reproducer...

```
(defun do-call (local-fun)
  (unwind-protect
       (funcall local-fun)
    (progn
      #+clasp(core:fflush)
      )))

(defun reproduce ()
  (block here
    (flet ((local-fun ()
             (return-from here (values :value))))
      (do-call #'local-fun))))

(defun do-reproduce ()
  (let ((result (multiple-value-list (reproduce))))
    (if result
        (format t "There is no problem~%")
        (format t "There is a PROBLEM~%"))))
```

**Comment by Bike** [comment]
New problem incidentally caused by my fix: protects ending in the same function as the `unwind-protect` go badly. For example:

```lisp
(block nil
  (mp:with-lock (some-lock)
    (apply (lambda (id) (return id)) (list 4))))
```

`mp:with-lock` expands to an unwind protect that takes care of the lock. In the course of cleanup, it executes `giveup-lock` which returns 0 values, editing the multiple values array as it does. These zero values end up returned from the form.
