### ISSUE TITLE
Errors in initialize_unix_signal_handlers, need to install function w/o arguments

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#956]
Hello,
I believe everything added in `initialize_unix_signal_handlers` must be a function with 0 arguments, since `handle_signal_now` will call with `core::eval::funcall(handler->symbolFunction());`

So probably wrong are:
* `#ifdef SIGSEGV
        ADD_SIGNAL( SIGSEGV, "SIGSEGV", ext::_sym_segmentation_violation);
#endif`
* `#ifdef SIGBUS
        ADD_SIGNAL( SIGBUS, "SIGBUS", ext::_sym_bus_error);
#endif`
and
* `#ifdef SIGCHLD
        ADD_SIGNAL( SIGCHLD, "SIGCHLD", core::_sym_wait_for_all_processes);
#endif`
since core::_sym_wait_for_all_processes does not have a function binding

Sigbus (if pr #955 is merged) and SIGSEGV are already handled in `initialize_signals` they probably can be deleted.

Not sure about `sym_wait_for_all_processes` can't find anything similar. Looking at the definition of SIGCHLD, it is also not clear what should happen

**Comment by Bike** [comment]
`SIGCHLD` is used in the forked build, so be careful about touching that one

**Comment by kpoeck** [comment]
closed with #955
